#
# Module manifest for module 'MicrosoftTeams'
#
# Generated by: Microsoft Corporation
#
# Updated on: 6/30/2020
#

@{
# Script module or binary module file associated with this manifest.
RootModule = './MicrosoftTeams.psm1'

# Version number of this module.
ModuleVersion = '3.0.0'

# Supported PSEditions
CompatiblePSEditions = 'Core', 'Desktop'

# ID used to uniquely identify this module
GUID = 'd910df43-3ca6-4c9c-a2e3-e9f45a8e2ad9'

# Author of this module
Author = 'Microsoft Corporation'

# Company or vendor of this module
CompanyName = 'Microsoft Corporation'

# Copyright statement for this module
Copyright = 'Microsoft Corporation. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Microsoft Teams cmdlets module for Windows PowerShell and PowerShell Core.

For more information, please visit the following: https://docs.microsoft.com/MicrosoftTeams/teams-powershell-overview'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
DotNetFrameworkVersion = '4.7.2'

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
CLRVersion = '4.0'

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = 'Amd64'

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
 ScriptsToProcess = @('.\SetMSTeamsReleaseEnvironment.ps1')

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = if($PSEdition -ne 'Desktop')
{
    '.\netcoreapp3.1\Microsoft.TeamsCmdlets.PowerShell.Connect.dll',
    '.\netcoreapp3.1\Microsoft.Teams.ConfigAPI.Cmdlets.psd1',
    '.\Microsoft.Teams.PowerShell.TeamsCmdlets.psd1'
}
else
{
    '.\net472\Microsoft.TeamsCmdlets.PowerShell.Connect.dll',
    '.\net472\Newtonsoft.Json.dll',
    '.\net472\Microsoft.Teams.ConfigAPI.Cmdlets.psd1',
    '.\Microsoft.Teams.PowerShell.TeamsCmdlets.psd1'
}

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport =  @(
   'Get-CsBatchPolicyAssignmentOperation'
   ,'Get-CsGroupPolicyAssignment'
   ,'Get-CsOnlinePowerShellEndpoint'
   ,'Get-CsPolicyPackage'
   ,'Get-CsUserPolicyAssignment'
   ,'Get-CsUserPolicyPackage'
   ,'Get-CsUserPolicyPackageRecommendation'
   ,'Grant-CsUserPolicyPackage'
   ,'New-CsBatchPolicyAssignmentOperation'
   ,'New-CsBatchPolicyPackageAssignmentOperation'
   ,'New-CsGroupPolicyAssignment'
   ,'Remove-CsGroupPolicyAssignment'
   ,'Move-CsInternalHelper'
   ,'Set-CsInternalOnlinePowerShellEndpoint'
   ,'Invoke-CsInternalPSTelemetry'
   ,'Grant-CsGroupPolicyPackageAssignment'
   ,'Get-CsTeamTemplateList'
   ,'Get-CsTeamTemplate'
   ,'Update-CsTeamTemplate'
   ,'New-CsTeamTemplate'
   ,'Remove-CsTeamTemplate'
   ,'New-CsCustomPolicyPackage'
   ,'Update-CsCustomPolicyPackage'
   ,'Remove-CsCustomPolicyPackage'
#Skype.TelephoneNumberMgmt Search V2
   ,'Get-CsOnlineTelephoneNumberCountry'
   ,'Get-CsOnlineTelephoneNumberType'
   ,'Get-CsOnlineTelephoneNumberOrder'
   ,'New-CsOnlineTelephoneNumberOrder'
   ,'Complete-CsOnlineTelephoneNumberOrder'
   ,'Clear-CsOnlineTelephoneNumberOrder'
#Skype.TelephoneNumberMgmt PhoneNumberAssignment
   ,'Set-CsPhoneNumberAssignment'
   ,'Remove-CsPhoneNumberAssignment'
#Audio File (autorest only)
   ,'Get-CsOnlineAudioFile'
   ,'Remove-CsOnlineAudioFile'
   ,'Export-CsOnlineAudioFile'
#Shift Connector
#preview    ,'Get-CsTeamsShiftsConnectionConnector'
#preview    ,'Test-CsTeamsShiftsConnectionValidate'
#preview    ,'New-CsTeamsShiftsConnectionInstance'
#preview    ,'Set-CsTeamsShiftsConnectionInstance'
#preview    ,'Remove-CsTeamsShiftsConnectionInstance'
#preview    ,'Get-CsTeamsShiftsConnectionInstance'
#preview    ,'Get-CsTeamsShiftsConnectionWfmTeam'
#preview    ,'New-CsTeamsShiftsConnectionTeamMap'
#preview    ,'Remove-CsTeamsShiftsConnectionTeamMap'
#preview    ,'Get-CsTeamsShiftsConnectionTeamMap'
#preview    ,'Get-CsTeamsShiftsConnectionSyncResult'
#preview    ,'Get-CsTeamsShiftsConnectionUser'
#preview    ,'Get-CsUserCallingSettings'
#preview    ,'Set-CsUserCallingSettings'
#SfBO: Begin
   ,'Clear-CsOnlineTelephoneNumberReservation'
   ,'ConvertTo-JsonForPSWS'
   ,'Disable-CsMeetingRoom'
   ,'Disable-CsOnlineDialInConferencingUser'
   ,'Disable-CsOnlineSipDomain'
   ,'Enable-CsMeetingRoom'
   ,'Enable-CsOnlineDialInConferencingUser'
   ,'Enable-CsOnlineSipDomain'
   ,'Export-CsAutoAttendantHolidays'
   ,'Find-CsGroup'
   ,'Find-CsOnlineApplicationInstance'
   ,'Get-CsApplicationAccessPolicy'
   ,'Get-CsApplicationMeetingConfiguration'
   ,'Get-CsAudioConferencingProvider'
   ,'Get-CsAutoAttendant'
   ,'Get-CsAutoAttendantHolidays'
   ,'Get-CsAutoAttendantStatus'
   ,'Get-CsAutoAttendantSupportedLanguage'
   ,'Get-CsAutoAttendantSupportedTimeZone'
   ,'Get-CsAutoAttendantTenantInformation'
   ,'Get-CsBroadcastMeetingConfiguration'
   ,'Get-CsBroadcastMeetingPolicy'
   ,'Get-CsCallingLineIdentity'
   ,'Get-CsCallQueue'
   ,'Get-CsClientPolicy'
   ,'Get-CsCloudCallDataConnection'
   ,'Get-CsCloudMeetingPolicy'
   ,'Get-CsConferencingPolicy'
   ,'Get-CsDefaultCatalogApp'
   ,'Get-CsDialPlan'
   ,'Get-CsEffectiveTenantDialPlan'
   ,'Get-CsExternalAccessPolicy'
   ,'Get-CsExternalUserCommunicationPolicy'
   ,'Get-CsGlobalCatalogApp'
   ,'Get-CsGraphPolicy'
   ,'Get-CsHostedVoicemailPolicy'
   ,'Get-CsHostingProvider'
   ,'Get-CsHybridMediationServer'
   ,'Get-CsHybridPSTNAppliance'
   ,'Get-CsHybridPSTNSite'
   ,'Get-CsImFilterConfiguration'
   ,'Get-CsInboundBlockedNumberPattern'
   ,'Get-CsInboundExemptNumberPattern'
   ,'Get-CsIPPhonePolicy'
   ,'Get-CsMeetingConfiguration'
   ,'Get-CsMeetingMigrationStatus'
   ,'Get-CsMeetingRoom'
   ,'Get-CsMobilityPolicy'
   ,'Get-CsNetworkConfiguration'
   ,'Get-CsOAuthConfiguration'
   ,'Get-CsOnlineApplicationEndpoint'
   ,'Get-CsOnlineApplicationInstance'
   ,'Get-CsOnlineApplicationInstanceAssociation'
   ,'Get-CsOnlineApplicationInstanceAssociationStatus'
   ,'Get-CsOnlineAudioConferencingRoutingPolicy'
   ,'Get-CsOnlineDialInConferencingBridge'
   ,'Get-CsOnlineDialInConferencingLanguagesSupported'
   ,'Get-CsOnlineDialinConferencingPolicy'
   ,'Get-CsOnlineDialInConferencingServiceNumber'
   ,'Get-CsOnlineDialinConferencingTenantConfiguration'
   ,'Get-CsOnlineDialInConferencingTenantSettings'
   ,'Get-CsOnlineDialInConferencingUser'
   ,'Get-CsOnlineDialInConferencingUserInfo'
   ,'Get-CsOnlineDialInConferencingUserState'
   ,'Get-CsOnlineDialOutPolicy'
   ,'Get-CsOnlineDirectoryTenant'
   ,'Get-CsOnlineDirectoryTenantNumberCities'
   ,'Get-CsOnlineEnhancedEmergencyServiceDisclaimer'
   ,'Get-CsOnlineLisCivicAddress'
   ,'Get-CsOnlineLisLocation'
   ,'Get-CsOnlineLisPort'
   ,'Get-CsOnlineLisSubnet'
   ,'Get-CsOnlineLisSwitch'
   ,'Get-CsOnlineLisWirelessAccessPoint'
   ,'Get-CsOnlineNumberPortInOrder'
   ,'Get-CsOnlineNumberPortOutOrderPin'
   ,'Get-CsOnlinePSTNGateway'
   ,'Get-CsOnlinePstnUsage'
   ,'Get-CsOnlineSchedule'
   ,'Get-CsOnlineSipDomain'
   ,'Get-CsOnlineTelephoneNumber'
   ,'Get-CsOnlineTelephoneNumberAvailableCount'
   ,'Get-CsOnlineTelephoneNumberInventoryAreas'
   ,'Get-CsOnlineTelephoneNumberInventoryCities'
   ,'Get-CsOnlineTelephoneNumberInventoryCountries'
   ,'Get-CsOnlineTelephoneNumberInventoryRegions'
   ,'Get-CsOnlineTelephoneNumberInventoryTypes'
   ,'Get-CsOnlineTelephoneNumberReservationsInformation'
   ,'Get-CsOnlineUser'
   ,'Get-CsOnlineVoicemailPolicy'
   ,'Get-CsOnlineVoicemailUserSettings'
   ,'Get-CsOnlineVoiceRoute'
   ,'Get-CsOnlineVoiceRoutingPolicy'
   ,'Get-CsOnlineVoiceUser'
   ,'Get-CsPrivacyConfiguration'
   ,'Get-CsPushNotificationConfiguration'
   ,'Get-CsTeamsAcsFederationConfiguration'
   ,'Get-CsTeamsAppPermissionPolicy'
   ,'Get-CsTeamsAppPreset'
   ,'Get-CsTeamsAppSetupPolicy'
   ,'Get-CsTeamsAudioConferencingPolicy'
   ,'Get-CsTeamsCallingPolicy'
   ,'Get-CsTeamsCallParkPolicy'
   ,'Get-CsTeamsCallHoldPolicy'
   ,'Get-CsTeamsChannelsPolicy'
   ,'Get-CsTeamsClientConfiguration'
   ,'Get-CsTeamsComplianceRecordingApplication'
   ,'Get-CsTeamsComplianceRecordingPolicy'
   ,'Get-CsTeamsCortanaPolicy'
   ,'Get-CsTeamsEducationAssignmentsAppPolicy'
   ,'Get-CsTeamsEmergencyCallingPolicy'
   ,'Get-CsTeamsEmergencyCallRoutingPolicy'
   ,'Get-CsTeamsFeedbackPolicy'
   ,'Get-CsTeamsGuestCallingConfiguration'
   ,'Get-CsTeamsGuestMeetingConfiguration'
   ,'Get-CsTeamsGuestMessagingConfiguration'
   ,'Get-CsTeamsIPPhonePolicy'
   ,'Get-CsTeamsMeetingBroadcastConfiguration'
   ,'Get-CsTeamsMeetingBroadcastPolicy'
   ,'Get-CsTeamsMeetingConfiguration'
   ,'Get-CsTeamsMeetingPolicy'
   ,'Get-CsTeamsMessagingPolicy'
   ,'Get-CsTeamsMigrationConfiguration'
   ,'Get-CsTeamsMobilityPolicy'
   ,'Get-CsTeamsNetworkRoamingPolicy'
   ,'Get-CsTeamsNotificationAndFeedsPolicy'
   ,'Get-CsTeamsPinnedApp'
   ,'Get-CsTeamsShiftsAppPolicy'
   ,'Get-CsTeamsShiftsPolicy'
   ,'Get-CsTeamsSurvivableBranchAppliance'
   ,'Get-CsTeamsSurvivableBranchAppliancePolicy'
   ,'Get-CsTeamsTargetingPolicy'
   ,'Get-CsTeamsTranslationRule'
   ,'Get-CsTeamsUpdateManagementPolicy'
   ,'Get-CsTeamsUpgradeConfiguration'
   ,'Get-CsTeamsUpgradePolicy'
   ,'Get-CsTeamsUpgradeStatus'
   ,'Get-CsTeamsVdiPolicy'
   ,'Get-CsTeamsVerticalPackagePolicy'
   ,'Get-CsTeamsVideoInteropServicePolicy'
   ,'Get-CsTeamsWorkLoadPolicy'
   ,'Get-CsTenant'
   ,'Get-CsTenantBlockedCallingNumbers'
   ,'Get-CsTeamsEnhancedEncryptionPolicy'
   ,'Get-CsTenantCatalogApp'
   ,'Get-CsTenantDialPlan'
   ,'Get-CsTenantFederationConfiguration'
   ,'Get-CsTenantHybridConfiguration'
   ,'Get-CsTenantLicensingConfiguration'
   ,'Get-CsTenantMigrationConfiguration'
   ,'Get-CsTenantNetworkConfiguration'
   ,'Get-CsTenantNetworkPostalCode'
   ,'Get-CsTenantNetworkRegion'
   ,'Get-CsTenantNetworkSite'
   ,'Get-CsTenantNetworkSubnet'
   ,'Get-CsTenantPublicProvider'
   ,'Get-CsTenantTrustedIPAddress'
   ,'Get-CsTenantUpdateTimeWindow'
   ,'Get-CsUCPhoneConfiguration'
   ,'Get-CsUserLocationStatus'
   ,'Get-CsUserPstnSettings'
   ,'Get-CsUserServicesPolicy'
   ,'Get-CsVideoInteropServiceProvider'
   ,'Get-CsVoiceNormalizationRule'
   ,'Get-CsVoiceRoutingPolicy'
   ,'Get-CsTeamsUnassignedNumberTreatment'
   ,'Get-CsTeamsFilesPolicy'
   ,'Grant-CsApplicationAccessPolicy'
   ,'Grant-CsBroadcastMeetingPolicy'
   ,'Grant-CsCallingLineIdentity'
   ,'Grant-CsClientPolicy'
   ,'Grant-CsCloudMeetingPolicy'
   ,'Grant-CsConferencingPolicy'
   ,'Grant-CsDialoutPolicy'
   ,'Grant-CsExternalAccessPolicy'
   ,'Grant-CsExternalUserCommunicationPolicy'
   ,'Grant-CsGraphPolicy'
   ,'Grant-CsHostedVoicemailPolicy'
   ,'Grant-CsIPPhonePolicy'
   ,'Grant-CsMobilityPolicy'
   ,'Grant-CsOnlineAudioConferencingRoutingPolicy'
   ,'Grant-CsOnlineVoicemailPolicy'
   ,'Grant-CsOnlineVoiceRoutingPolicy'
   ,'Grant-CsPolicy'
   ,'Grant-CsTeamsAppPermissionPolicy'
   ,'Grant-CsTeamsAppSetupPolicy'
   ,'Grant-CsTeamsAudioConferencingPolicy'
   ,'Grant-CsTeamsCallingPolicy'
   ,'Grant-CsTeamsCallParkPolicy'
   ,'Grant-CsTeamsCallHoldPolicy'
   ,'Grant-CsTeamsChannelsPolicy'
   ,'Grant-CsTeamsComplianceRecordingPolicy'
   ,'Grant-CsTeamsCortanaPolicy'
   ,'Grant-CsTeamsEmergencyCallingPolicy'
   ,'Grant-CsTeamsEmergencyCallRoutingPolicy'
   ,'Grant-CsTeamsFeedbackPolicy'
   ,'Grant-CsTeamsIPPhonePolicy'
   ,'Grant-CsTeamsMeetingBroadcastPolicy'
   ,'Grant-CsTeamsMeetingPolicy'
   ,'Grant-CsTeamsMessagingPolicy'
   ,'Grant-CsTeamsMobilityPolicy'
   ,'Grant-CsTeamsShiftsPolicy'
   ,'Grant-CsTeamsSurvivableBranchAppliancePolicy'
   ,'Grant-CsTeamsUpdateManagementPolicy'
   ,'Grant-CsTeamsUpgradePolicy'
   ,'Grant-CsTeamsVdiPolicy'
   ,'Grant-CsTeamsVerticalPackagePolicy'
   ,'Grant-CsTeamsVideoInteropServicePolicy'
   ,'Grant-CsTeamsWorkLoadPolicy'
   ,'Grant-CsTenantDialPlan'
   ,'Grant-CsVoiceRoutingPolicy'
   ,'Grant-CsTeamsEnhancedEncryptionPolicy'
   ,'Grant-CsTeamsFilesPolicy'
   ,'Import-CsAutoAttendantHolidays'
   ,'Import-CsOnlineAudioFile'
   ,'Invoke-CsUcsRollback'
   ,'Invoke-CsUserPreferredDataLocationSync'
   ,'New-CsApplicationAccessPolicy'
   ,'New-CsAutoAttendant'
   ,'New-CsAutoAttendantCallableEntity'
   ,'New-CsAutoAttendantCallFlow'
   ,'New-CsAutoAttendantCallHandlingAssociation'
   ,'New-CsAutoAttendantDialScope'
   ,'New-CsAutoAttendantMenu'
   ,'New-CsAutoAttendantMenuOption'
   ,'New-CsAutoAttendantPrompt'
   ,'New-CsCallingLineIdentity'
   ,'New-CsCallQueue'
   ,'New-CsClientPolicy'
   ,'New-CsCloudCallDataConnection'
   ,'New-CsConferencingPolicy'
   ,'New-CsDefaultCatalogApp'
   ,'New-CsEdgeAllowAllKnownDomains'
   ,'New-CsEdgeAllowList'
   ,'New-CsEdgeDomainPattern'
   ,'New-CsExternalAccessPolicy'
   ,'New-CsExternalUserCommunicationPolicy'
   ,'New-CsGlobalCatalogApp'
   ,'New-CsHybridPSTNSite'
   ,'New-CsHybridTelephoneNumber'
   ,'New-CsInboundBlockedNumberPattern'
   ,'New-CsInboundExemptNumberPattern'
   ,'New-CsMobilityPolicy'
   ,'New-CsNetworkMediaBypassConfiguration'
   ,'New-CsOnlineApplicationEndpoint'
   ,'New-CsOnlineApplicationInstance'
   ,'New-CsOnlineApplicationInstanceAssociation'
   ,'New-CsOnlineAudioConferencingRoutingPolicy'
   ,'New-CsOnlineAudioFile'
   ,'New-CsOnlineBulkAssignmentInput'
   ,'New-CsOnlineDateTimeRange'
   ,'New-CsOnlineLisCivicAddress'
   ,'New-CsOnlineLisLocation'
   ,'New-CsOnlineNumberPortInOrder'
   ,'New-CsOnlinePSTNGateway'
   ,'New-CsOnlineSchedule'
   ,'New-CsOnlineTimeRange'
   ,'New-CsOnlineVoicemailPolicy'
   ,'New-CsOnlineVoiceRoute'
   ,'New-CsOnlineVoiceRoutingPolicy'
   ,'New-CsTeamsAppPermissionPolicy'
   ,'New-CsTeamsAppPreset'
   ,'New-CsTeamsAppSetupPolicy'
   ,'New-CsTeamsAudioConferencingPolicy'
   ,'New-CsTeamsCallingPolicy'
   ,'New-CsTeamsCallParkPolicy'
   ,'New-CsTeamsCallHoldPolicy'
   ,'New-CsTeamsChannelsPolicy'
   ,'New-CsTeamsComplianceRecordingApplication'
   ,'New-CsTeamsComplianceRecordingPairedApplication'
   ,'New-CsTeamsComplianceRecordingPolicy'
   ,'New-CsTeamsCortanaPolicy'
   ,'New-CsTeamsEmergencyCallingPolicy'
   ,'New-CsTeamsEmergencyCallRoutingPolicy'
   ,'New-CsTeamsEmergencyNumber'
   ,'New-CsTeamsFeedbackPolicy'
   ,'New-CsTeamsIPPhonePolicy'
   ,'New-CsTeamsMeetingBroadcastPolicy'
   ,'New-CsTeamsMeetingPolicy'
   ,'New-CsTeamsMessagingPolicy'
   ,'New-CsTeamsMobilityPolicy'
   ,'New-CsTeamsNetworkRoamingPolicy'
   ,'New-CsTeamsPinnedApp'
   ,'New-CsTeamsShiftsPolicy'
   ,'New-CsTeamsSurvivableBranchAppliance'
   ,'New-CsTeamsSurvivableBranchAppliancePolicy'
   ,'New-CsTeamsTranslationRule'
   ,'New-CsTeamsUpdateManagementPolicy'
   ,'New-CsTeamsVdiPolicy'
   ,'New-CsTeamsVerticalPackagePolicy'
   ,'New-CsTeamsWorkLoadPolicy'
   ,'New-CsTeamsEnhancedEncryptionPolicy'
   ,'New-CsTenantCatalogApp'
   ,'New-CsTenantDialPlan'
   ,'New-CsTenantNetworkPostalCode'
   ,'New-CsTenantNetworkRegion'
   ,'New-CsTenantNetworkSite'
   ,'New-CsTenantNetworkSubnet'
   ,'New-CsTenantTrustedIPAddress'
   ,'New-CsTenantUpdateTimeWindow'
   ,'New-CsVideoInteropServiceProvider'
   ,'New-CsVoiceNormalizationRule'
   ,'New-CsTeamsUnassignedNumberTreatment'
   ,'New-CsTeamsFilesPolicy'
   ,'Register-CsHybridPSTNAppliance'
   ,'Register-CsOnlineDialInConferencingServiceNumber'
   ,'Remove-CsApplicationAccessPolicy'
   ,'Remove-CsAutoAttendant'
   ,'Remove-CsCallingLineIdentity'
   ,'Remove-CsCallQueue'
   ,'Remove-CsClientPolicy'
   ,'Remove-CsConferencingPolicy'
   ,'Remove-CsDefaultCatalogApp'
   ,'Remove-CsExternalAccessPolicy'
   ,'Remove-CsExternalUserCommunicationPolicy'
   ,'Remove-CsGlobalCatalogApp'
   ,'Remove-CsHybridPSTNSite'
   ,'Remove-CsHybridTelephoneNumber'
   ,'Remove-CsInboundBlockedNumberPattern'
   ,'Remove-CsInboundExemptNumberPattern'
   ,'Remove-CsMobilityPolicy'
   ,'Remove-CsOnlineApplicationEndpoint'
   ,'Remove-CsOnlineApplicationInstanceAssociation'
   ,'Remove-CsOnlineAudioConferencingRoutingPolicy'
   ,'Remove-CsOnlineDialInConferencingTenantSettings'
   ,'Remove-CsOnlineLisCivicAddress'
   ,'Remove-CsOnlineLisLocation'
   ,'Remove-CsOnlineLisPort'
   ,'Remove-CsOnlineLisSubnet'
   ,'Remove-CsOnlineLisSwitch'
   ,'Remove-CsOnlineLisWirelessAccessPoint'
   ,'Remove-CsOnlineNumberPortInOrder'
   ,'Remove-CsOnlinePSTNGateway'
   ,'Remove-CsOnlineSchedule'
   ,'Remove-CsOnlineTelephoneNumber'
   ,'Remove-CsOnlineVoicemailPolicy'
   ,'Remove-CsOnlineVoiceRoute'
   ,'Remove-CsOnlineVoiceRoutingPolicy'
   ,'Remove-CsTeamsAppPermissionPolicy'
   ,'Remove-CsTeamsAppPreset'
   ,'Remove-CsTeamsAppSetupPolicy'
   ,'Remove-CsTeamsAudioConferencingPolicy'
   ,'Remove-CsTeamsCallingPolicy'
   ,'Remove-CsTeamsCallParkPolicy'
   ,'Remove-CsTeamsCallHoldPolicy'
   ,'Remove-CsTeamsChannelsPolicy'
   ,'Remove-CsTeamsComplianceRecordingApplication'
   ,'Remove-CsTeamsComplianceRecordingPolicy'
   ,'Remove-CsTeamsCortanaPolicy'
   ,'Remove-CsTeamsEmergencyCallingPolicy'
   ,'Remove-CsTeamsEmergencyCallRoutingPolicy'
   ,'Remove-CsTeamsFeedbackPolicy'
   ,'Remove-CsTeamsIPPhonePolicy'
   ,'Remove-CsTeamsMeetingBroadcastPolicy'
   ,'Remove-CsTeamsMeetingPolicy'
   ,'Remove-CsTeamsMessagingPolicy'
   ,'Remove-CsTeamsMobilityPolicy'
   ,'Remove-CsTeamsNetworkRoamingPolicy'
   ,'Remove-CsTeamsNotificationAndFeedsPolicy'
   ,'Remove-CsTeamsPinnedApp'
   ,'Remove-CsTeamsShiftsPolicy'
   ,'Remove-CsTeamsSurvivableBranchAppliance'
   ,'Remove-CsTeamsSurvivableBranchAppliancePolicy'
   ,'Remove-CsTeamsTargetingPolicy'
   ,'Remove-CsTeamsTranslationRule'
   ,'Remove-CsTeamsUpdateManagementPolicy'
   ,'Remove-CsTeamsVdiPolicy'
   ,'Remove-CsTeamsVerticalPackagePolicy'
   ,'Remove-CsTeamsWorkLoadPolicy'
   ,'Remove-CsTeamsEnhancedEncryptionPolicy'
   ,'Remove-CsTenantCatalogApp'
   ,'Remove-CsTenantDialPlan'
   ,'Remove-CsTenantNetworkConfiguration'
   ,'Remove-CsTenantNetworkPostalCode'
   ,'Remove-CsTenantNetworkRegion'
   ,'Remove-CsTenantNetworkSite'
   ,'Remove-CsTenantNetworkSubnet'
   ,'Remove-CsTenantTrustedIPAddress'
   ,'Remove-CsTenantUpdateTimeWindow'
   ,'Remove-CsVideoInteropServiceProvider'
   ,'Remove-CsVoiceNormalizationRule'
   ,'Remove-CsTeamsUnassignedNumberTreatment'
   ,'Remove-CsTeamsFilesPolicy'
   ,'Search-CsOnlineTelephoneNumberInventory'
   ,'Select-CsOnlineTelephoneNumberInventory'
   ,'Set-CsApplicationAccessPolicy'
   ,'Set-CsApplicationMeetingConfiguration'
   ,'Set-CsAutoAttendant'
   ,'Set-CsBroadcastMeetingConfiguration'
   ,'Set-CsCallingLineIdentity'
   ,'Set-CsCallQueue'
   ,'Set-CsCceApplianceConfigurationReplicationStatus'
   ,'Set-CsCceApplianceDeploymentStatus'
   ,'Set-CsCceApplianceStatus'
   ,'Set-CsClientPolicy'
   ,'Set-CsConferencingPolicy'
   ,'Set-CsDefaultCatalogApp'
   ,'Set-CsExternalAccessPolicy'
   ,'Set-CsExternalUserCommunicationPolicy'
   ,'Set-CsGlobalCatalogApp'
   ,'Set-CsHybridMediationServer'
   ,'Set-CsHybridPSTNAppliance'
   ,'Set-CsHybridPSTNSite'
   ,'Set-CsInboundBlockedNumberPattern'
   ,'Set-CsInboundExemptNumberPattern'
   ,'Set-CsIPPhonePolicy'
   ,'Set-CsMeetingConfiguration'
   ,'Set-CsMeetingRoom'
   ,'Set-CsMobilityPolicy'
   ,'Set-CsNetworkConfiguration'
   ,'Set-CsOAuthConfiguration'
   ,'Set-CsOnlineApplicationEndpoint'
   ,'Set-CsOnlineApplicationInstance'
   ,'Set-CsOnlineAudioConferencingRoutingPolicy'
   ,'Set-CsOnlineDialInConferencingBridge'
   ,'Set-CsOnlineDialInConferencingServiceNumber'
   ,'Set-CsOnlineDialInConferencingTenantSettings'
   ,'Set-CsOnlineDialInConferencingUser'
   ,'Set-CsOnlineDialInConferencingUserDefaultNumber'
   ,'Set-CsOnlineDirectoryUser'
   ,'Set-CsOnlineEnhancedEmergencyServiceDisclaimer'
   ,'Set-CsOnlineLisCivicAddress'
   ,'Set-CsOnlineLisLocation'
   ,'Set-CsOnlineLisPort'
   ,'Set-CsOnlineLisSubnet'
   ,'Set-CsOnlineLisSwitch'
   ,'Set-CsOnlineLisWirelessAccessPoint'
   ,'Set-CsOnlineNumberPortInOrder'
   ,'Set-CsOnlineNumberPortOutOrderPin'
   ,'Set-CsOnlinePSTNGateway'
   ,'Set-CsOnlinePstnUsage'
   ,'Set-CsOnlineSchedule'
   ,'Set-CsOnlineVoiceApplicationInstance'
   ,'Set-CsOnlineVoicemailPolicy'
   ,'Set-CsOnlineVoicemailUserSettings'
   ,'Set-CsOnlineVoiceRoute'
   ,'Set-CsOnlineVoiceRoutingPolicy'
   ,'Set-CsOnlineVoiceUser'
   ,'Set-CsOnlineVoiceUserBulk'
   ,'Set-CsPrivacyConfiguration'
   ,'Set-CsPushNotificationConfiguration'
   ,'Set-CsTeamsAcsFederationConfiguration'
   ,'Set-CsTeamsAppPermissionPolicy'
   ,'Set-CsTeamsAppPreset'
   ,'Set-CsTeamsAppSetupPolicy'
   ,'Set-CsTeamsAudioConferencingPolicy'
   ,'Set-CsTeamsCallingPolicy'
   ,'Set-CsTeamsCallParkPolicy'
   ,'Set-CsTeamsCallHoldPolicy'
   ,'Set-CsTeamsChannelsPolicy'
   ,'Set-CsTeamsClientConfiguration'
   ,'Set-CsTeamsComplianceRecordingApplication'
   ,'Set-CsTeamsComplianceRecordingPolicy'
   ,'Set-CsTeamsCortanaPolicy'
   ,'Set-CsTeamsEducationAssignmentsAppPolicy'
   ,'Set-CsTeamsEmergencyCallingPolicy'
   ,'Set-CsTeamsEmergencyCallRoutingPolicy'
   ,'Set-CsTeamsFeedbackPolicy'
   ,'Set-CsTeamsGuestCallingConfiguration'
   ,'Set-CsTeamsGuestMeetingConfiguration'
   ,'Set-CsTeamsGuestMessagingConfiguration'
   ,'Set-CsTeamsIPPhonePolicy'
   ,'Set-CsTeamsMeetingBroadcastConfiguration'
   ,'Set-CsTeamsMeetingBroadcastPolicy'
   ,'Set-CsTeamsMeetingConfiguration'
   ,'Set-CsTeamsMeetingPolicy'
   ,'Set-CsTeamsMessagingPolicy'
   ,'Set-CsTeamsMigrationConfiguration'
   ,'Set-CsTeamsMobilityPolicy'
   ,'Set-CsTeamsNetworkRoamingPolicy'
   ,'Set-CsTeamsNotificationAndFeedsPolicy'
   ,'Set-CsTeamsPinnedApp'
   ,'Set-CsTeamsShiftsAppPolicy'
   ,'Set-CsTeamsShiftsPolicy'
   ,'Set-CsTeamsSurvivableBranchAppliance'
   ,'Set-CsTeamsSurvivableBranchAppliancePolicy'
   ,'Set-CsTeamsTargetingPolicy'
   ,'Set-CsTeamsTranslationRule'
   ,'Set-CsTeamsUpdateManagementPolicy'
   ,'Set-CsTeamsUpgradeConfiguration'
   ,'Set-CsTeamsUpgradeStatus'
   ,'Set-CsTeamsVdiPolicy'
   ,'Set-CsTeamsVerticalPackagePolicy'
   ,'Set-CsTeamsWorkLoadPolicy'
   ,'Set-CsTenantBlockedCallingNumbers'
   ,'Set-CsTeamsEnhancedEncryptionPolicy'
   ,'Set-CsTenantCatalogApp'
   ,'Set-CsTenantDialPlan'
   ,'Set-CsTenantFederationConfiguration'
   ,'Set-CsTenantHybridConfiguration'
   ,'Set-CsTenantMigrationConfiguration'
   ,'Set-CsTenantNetworkConfiguration'
   ,'Set-CsTenantNetworkPostalCode'
   ,'Set-CsTenantNetworkRegion'
   ,'Set-CsTenantNetworkSite'
   ,'Set-CsTenantNetworkSubnet'
   ,'Set-CsTenantPublicProvider'
   ,'Set-CsTenantTrustedIPAddress'
   ,'Set-CsTenantUpdateTimeWindow'
   ,'Set-CsUCPhoneConfiguration'
   ,'Set-CsUser'
   ,'Set-CsUserPstnSettings'
   ,'Set-CsUserServicesPolicy'
   ,'Set-CsVideoInteropServiceProvider'
   ,'Set-CsVoiceNormalizationRule'
   ,'Set-CsTeamsUnassignedNumberTreatment'
   ,'Set-CsTeamsFilesPolicy'
   ,'Start-CsExMeetingMigration'
   ,'Switch-CsOnlineApplicationEndpoint'
   ,'Sync-CsOnlineApplicationInstance'
   ,'Test-CsEffectiveTenantDialPlan'
   ,'Test-CsInboundBlockedNumberPattern'
   ,'Test-CsOnlineCarrierPortabilityIn'
   ,'Test-CsOnlineLisCivicAddress'
   ,'Test-CsOnlinePortabilityIn'
   ,'Test-CsVoiceNormalizationRule'
   ,'Unregister-CsHybridPSTNAppliance'
   ,'Unregister-CsOnlineDialInConferencingServiceNumber'
   ,'Update-CsAutoAttendant'
   ,'Update-CsTenantMeetingUrl'
#SfBO: End
)
# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @(
    'Add-TeamChannelUser'
    ,'Add-TeamUser'
    ,'Connect-MicrosoftTeams'
    ,'Disconnect-MicrosoftTeams'
    ,'Get-MultiGeoRegion'
    ,'Get-Operation'
    ,'Get-Team'
    ,'Get-TeamChannel'
    ,'Get-TeamChannelUser'
    ,'Get-TeamsApp'
    ,'Get-TeamUser'
    ,'New-Team'
    ,'New-TeamChannel'
    ,'New-TeamsApp'
    ,'Remove-Team'
    ,'Remove-TeamChannel'
    ,'Remove-TeamChannelUser'
    ,'Remove-TeamsApp'
    ,'Remove-TeamUser'
    ,'Set-Team'
    ,'Set-TeamArchivedState'
    ,'Set-TeamChannel'
    ,'Set-TeamPicture'
    ,'Set-TeamsApp'
#preview    ,'Add-TeamsAppInstallation'
#preview    ,'Get-TeamsAppInstallation'
#preview    ,'Get-TeamTargetingHierarchyStatus'
#preview    ,'Remove-TeamsAppInstallation'
#preview    ,'Remove-TeamTargetingHierarchy'
#preview    ,'Set-TeamTargetingHierarchy'
#preview    ,'Update-TeamsAppInstallation'
#preview    ,'Get-LicenseReportForChangeNotificationSubscription'
 )

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = '*'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{
    PSData = @{
        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Office365', 'MicrosoftTeams', 'Teams'

        # A URL to the license for this module.
        LicenseUri = 'https://raw.githubusercontent.com/MicrosoftDocs/office-docs-powershell/master/teams/LICENSE.txt'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/MicrosoftDocs/office-docs-powershell/tree/master/teams'

        # A URL to an icon representing this module.
        IconUri = 'https://statics.teams.microsoft.com/evergreen-assets/apps/teamscmdlets_largeimage.png'

        # Appends prerelease string to version
        Prerelease = ''

        # ReleaseNotes of this module
        ReleaseNotes = @'
 **3.0.0-GA** (The project - MicrosoftTeams contains these changes so far for this release)

- Soon MicrosoftTeams versions in the 3.x.x series will be the only versions supported. And all the older versions will be on the deprecation path.
- Releases modernized versions of all 75+ Grant-Cs<Name>Policy cmdlets (all parameter sets). These are expected to work similar to their remoting counter parts. The modern versions will be gradually rolled out. So some tenants will see the older remoting version (until the rollout completes).
- Releases modernized versions of all 75+ Remove-Cs<Name>Policy cmdlets. These are expected to work similar to their remoting counter parts. The modern versions will be gradually rolled out. So some tenants will see the older remoting version (until the rollout completes).
- Releases [Set|Remove]-CsPhoneNumberAssignment cmdlets. These cmdlets will be gradually rolled out. So some tenants will get an error message referencing the existing cmdlets they can use (until the rollout completes).
- Releases new parameter EnhancedEmergencyServiceDisclaimer for [Set|New]-CsTeamsEmergencyCallingPolicy cmdlet.
- Releases [Get|Add|Remove]-TeamChannelUser cmdlets.
- Releases Export-CsOnlineAudioFile cmdlet.
- Fixes error handlings for [Get|Import|Remove]-CsOnlineAudioFile cmdlets.
- [BREAKING CHANGE] Get-CsOnlineUser and Get-CsOnlineVoiceUser: The following changes apply for TeamsOnly tenants:
  - These cmdlets have now been migrated from the older implementation to the newer APIs.
  - (Using -Identity parameter): Attributes that are no longer relevant for Teams have been deprecated for TeamsOnly Tenants. Some attributes have also been renamed/replaced - Details [here](https://docs.microsoft.com/en-us/powershell/module/skype/get-csonlineuser?view=skype-ps) for Get-CsOnlineUser and [here](https://docs.microsoft.com/en-us/powershell/module/skype/get-csonlinevoiceuser?view=skype-ps) for Get-CsOnlineVoiceUser
  - Get-CsOnlineUser (with -Filter parameter):  Formatting for filtering based on AssignedPlans and EnterpriseVoice have been modified. Filterable attributes have also been temporarily limited (based on usage) for TeamsOnly Users - Details [here](https://docs.microsoft.com/en-us/powershell/module/skype/get-csonlinevoiceuser?view=skype-ps)
  - These cmdlets will be gradually rolled out and some tenants will not experience above changes until the rollout is completed by the end of CY21
- [BREAKING CHANGE] Get-CsTenant: Attributes that are no longer relevant in the Teams world have been deprecated for TeamsOnly tenants - Details [here](https://docs.microsoft.com/en-us/powershell/module/skype/get-cstenant?view=skype-ps)
- Fixes for Get-Team error handling. Output the error message if fetching teams data fails.
- Fixes for Connect-MicrosoftTeams, AccessTokens expiry diff time increased.
- The complete release notes can be found in the below link:
https://docs.microsoft.com/MicrosoftTeams/teams-powershell-release-notes
'@
    } # End of PSData hashtable
} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''
}

# SIG # Begin signature block
# MIInpAYJKoZIhvcNAQcCoIInlTCCJ5ECAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCCGAfT6xZkzubMU
# E5I+zb2MjTOrJIpBBYHw7ovakLWOcqCCDXMwggXxMIID2aADAgECAhMzAAACGYwK
# n7IWKxDmAAAAAAIZMA0GCSqGSIb3DQEBCwUAMH4xCzAJBgNVBAYTAlVTMRMwEQYD
# VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNpZ25p
# bmcgUENBIDIwMTEwHhcNMjEwNDI5MTkxMjU1WhcNMjIwNDI4MTkxMjU1WjByMQsw
# CQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9u
# ZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMRwwGgYDVQQDExNTa3lw
# ZSBTb2Z0d2FyZSBTYXJsMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
# nxMscK0w8ebaayvQhxPtLTkomfivSX4yNLmQJGXG+1yUKU4fmdQAhZm5mSIdFAEv
# sjAwCP3vUmh2N5R5TrAN/whfjGcDDlCYonKcrmuSaXxGuyjXKlELlRmPOaobqeo1
# 1Amcz6SRbNYBtKtRiP5ip2PfAvtJp7AvH0mZfGXKehE4C+5t8XYZ3K1JU3Tdb+3Z
# z+smovI8h/ZPe+uV2ORTxxa9kBLDvueJZbzKkn/WAIX/8rq/ywHtffSTXSueUmoe
# NJ0UCyoNBr90xtnozaCVknyRG8qWzHEZlc43FPNwIW6y8k1JSuspq+SML/HP7Fjv
# 7zcTLtM1HBBX/I9KxBJSBQIDAQABo4IBcjCCAW4wEwYDVR0lBAwwCgYIKwYBBQUH
# AwMwHQYDVR0OBBYEFAZqNYGuvWVnCVhV5aJBAvx4cJdwMFAGA1UdEQRJMEekRTBD
# MSkwJwYDVQQLEyBNaWNyb3NvZnQgT3BlcmF0aW9ucyBQdWVydG8gUmljbzEWMBQG
# A1UEBRMNMjMwMjU0KzQ2NDU2MjAfBgNVHSMEGDAWgBRIbmTlUAXTgqoXNzcitW2o
# ynUClTBUBgNVHR8ETTBLMEmgR6BFhkNodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20v
# cGtpb3BzL2NybC9NaWNDb2RTaWdQQ0EyMDExXzIwMTEtMDctMDguY3JsMGEGCCsG
# AQUFBwEBBFUwUzBRBggrBgEFBQcwAoZFaHR0cDovL3d3dy5taWNyb3NvZnQuY29t
# L3BraW9wcy9jZXJ0cy9NaWNDb2RTaWdQQ0EyMDExXzIwMTEtMDctMDguY3J0MAwG
# A1UdEwEB/wQCMAAwDQYJKoZIhvcNAQELBQADggIBABRKE3yDcJHa8xnyFn9Z+0m8
# vQLeUGC9933o78aSOWDkvcPFPczSqvw4cUmQnHPcRwDS1mwlYs5TmCdIS6Ij++Or
# uWxfgMdPRpveO6zT8rDWBL2sqCT/k5yCO75DVhT4kE/qEe81T4OY/Ejx3lZbBE1a
# z2k5dOL/ZWqNu8FdKSDmBZEeENOYy9UIyLf6coV2KLERB2IZ3W8U3z37fPA5nRMw
# +9sWWb98Gdm8exr4UwmnU0q8Y0KvJx/xwqOPShgiDjHsWev3fzsKSYzebkfBdLbw
# DZl9880mrGr03CfEWGDWa0tJui3LRh4csIuxWHkUrFw/R2N8baMDGPEUCh7dE+qf
# nuuMJ5tRUmnMOqyqj8dLXUZa+yxxpS91qde5asle0+WfzjLQ1D+T6ElhLBQU9LNh
# 5nhbD1+kJkVHFAU2tM3MXa2tgMVWFWQP4IqcQDWMW68M90VkGUrJ+t63oRO8HwbL
# 4IZJxG0wW/527ypSQTmpLSX6mM2vIyFHsO4zCvjDq8yfnDk25bpUNJbfOpqVkkWP
# UE+4bNIQbzcWgKgPIZDOka3pxq4vI05ns3tnvWS7TKiG+7ZYr5ZBSS6pr1Wykt0U
# aXxaUZuAWwikj2gvZAXR35f5bDg+36WoJTpQKNqzsY7dyL6SxkcZI8DcEKWEfbWd
# BX8q+w5hzEWqh7TrYJ93MIIHejCCBWKgAwIBAgIKYQ6Q0gAAAAAAAzANBgkqhkiG
# 9w0BAQsFADCBiDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAO
# BgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEy
# MDAGA1UEAxMpTWljcm9zb2Z0IFJvb3QgQ2VydGlmaWNhdGUgQXV0aG9yaXR5IDIw
# MTEwHhcNMTEwNzA4MjA1OTA5WhcNMjYwNzA4MjEwOTA5WjB+MQswCQYDVQQGEwJV
# UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UE
# ChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSgwJgYDVQQDEx9NaWNyb3NvZnQgQ29k
# ZSBTaWduaW5nIFBDQSAyMDExMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKC
# AgEAq/D6chAcLq3YbqqCEE00uvK2WCGfQhsqa+laUKq4BjgaBEm6f8MMHt03a8YS
# 2AvwOMKZBrDIOdUBFDFC04kNeWSHfpRgJGyvnkmc6Whe0t+bU7IKLMOv2akrrnoJ
# r9eWWcpgGgXpZnboMlImEi/nqwhQz7NEt13YxC4Ddato88tt8zpcoRb0RrrgOGSs
# bmQ1eKagYw8t00CT+OPeBw3VXHmlSSnnDb6gE3e+lD3v++MrWhAfTVYoonpy4BI6
# t0le2O3tQ5GD2Xuye4Yb2T6xjF3oiU+EGvKhL1nkkDstrjNYxbc+/jLTswM9sbKv
# kjh+0p2ALPVOVpEhNSXDOW5kf1O6nA+tGSOEy/S6A4aN91/w0FK/jJSHvMAhdCVf
# GCi2zCcoOCWYOUo2z3yxkq4cI6epZuxhH2rhKEmdX4jiJV3TIUs+UsS1Vz8kA/DR
# elsv1SPjcF0PUUZ3s/gA4bysAoJf28AVs70b1FVL5zmhD+kjSbwYuER8ReTBw3J6
# 4HLnJN+/RpnF78IcV9uDjexNSTCnq47f7Fufr/zdsGbiwZeBe+3W7UvnSSmnEyim
# p31ngOaKYnhfsi+E11ecXL93KCjx7W3DKI8sj0A3T8HhhUSJxAlMxdSlQy90lfdu
# +HggWCwTXWCVmj5PM4TasIgX3p5O9JawvEagbJjS4NaIjAsCAwEAAaOCAe0wggHp
# MBAGCSsGAQQBgjcVAQQDAgEAMB0GA1UdDgQWBBRIbmTlUAXTgqoXNzcitW2oynUC
# lTAZBgkrBgEEAYI3FAIEDB4KAFMAdQBiAEMAQTALBgNVHQ8EBAMCAYYwDwYDVR0T
# AQH/BAUwAwEB/zAfBgNVHSMEGDAWgBRyLToCMZBDuRQFTuHqp8cx0SOJNDBaBgNV
# HR8EUzBRME+gTaBLhklodHRwOi8vY3JsLm1pY3Jvc29mdC5jb20vcGtpL2NybC9w
# cm9kdWN0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFfMDNfMjIuY3JsMF4GCCsGAQUF
# BwEBBFIwUDBOBggrBgEFBQcwAoZCaHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3Br
# aS9jZXJ0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFfMDNfMjIuY3J0MIGfBgNVHSAE
# gZcwgZQwgZEGCSsGAQQBgjcuAzCBgzA/BggrBgEFBQcCARYzaHR0cDovL3d3dy5t
# aWNyb3NvZnQuY29tL3BraW9wcy9kb2NzL3ByaW1hcnljcHMuaHRtMEAGCCsGAQUF
# BwICMDQeMiAdAEwAZQBnAGEAbABfAHAAbwBsAGkAYwB5AF8AcwB0AGEAdABlAG0A
# ZQBuAHQALiAdMA0GCSqGSIb3DQEBCwUAA4ICAQBn8oalmOBUeRou09h0ZyKbC5YR
# 4WOSmUKWfdJ5DJDBZV8uLD74w3LRbYP+vj/oCso7v0epo/Np22O/IjWll11lhJB9
# i0ZQVdgMknzSGksc8zxCi1LQsP1r4z4HLimb5j0bpdS1HXeUOeLpZMlEPXh6I/MT
# faaQdION9MsmAkYqwooQu6SpBQyb7Wj6aC6VoCo/KmtYSWMfCWluWpiW5IP0wI/z
# Rive/DvQvTXvbiWu5a8n7dDd8w6vmSiXmE0OPQvyCInWH8MyGOLwxS3OW560STkK
# xgrCxq2u5bLZ2xWIUUVYODJxJxp/sfQn+N4sOiBpmLJZiWhub6e3dMNABQamASoo
# PoI/E01mC8CzTfXhj38cbxV9Rad25UAqZaPDXVJihsMdYzaXht/a8/jyFqGaJ+HN
# pZfQ7l1jQeNbB5yHPgZ3BtEGsXUfFL5hYbXw3MYbBL7fQccOKO7eZS/sl/ahXJbY
# ANahRr1Z85elCUtIEJmAH9AAKcWxm6U/RXceNcbSoqKfenoi+kiVH6v7RyOA9Z74
# v2u3S5fi63V4GuzqN5l5GEv/1rMjaHXmr/r8i+sLgOppO6/8MO0ETI7f33VtY5E9
# 0Z1WTk+/gFcioXgRMiF670EKsT/7qMykXcGhiJtXcVZOSEXAQsmbdlsKgEhr/Xmf
# wb1tbWrJUnMTDXpQzTGCGYcwghmDAgEBMIGVMH4xCzAJBgNVBAYTAlVTMRMwEQYD
# VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNpZ25p
# bmcgUENBIDIwMTECEzMAAAIZjAqfshYrEOYAAAAAAhkwDQYJYIZIAWUDBAIBBQCg
# gaYwGQYJKoZIhvcNAQkDMQwGCisGAQQBgjcCAQQwHAYKKwYBBAGCNwIBCzEOMAwG
# CisGAQQBgjcCARUwLwYJKoZIhvcNAQkEMSIEINTeC+vQN0EYYb0gHppp1Rvo67hJ
# Hhke0DFQzIXZbEvcMDoGCisGAQQBgjcCAQwxLDAqoAyACgBTAGsAeQBwAGWhGoAY
# aHR0cDovL3d3dy5taWNyb3NvZnQuY29tMA0GCSqGSIb3DQEBAQUABIIBACIH3Nwq
# hYqImb3DregCHLJD2Xv9M6Y1ryKJ6448Ud3hPGEoU1lgDGqE1CNBwIcHdPzds/g2
# JaZ+dfjdao3hgWiP/KwF8Ihk8fqHYTKr9qNX3jb77XiN3nop+Uwk2i/iPPIQ/5wc
# PeByPsa6NcMYUtdc5UUi3V+CthZyPYN35CuKK3jCrF2UIdvOUetcsGmfymAlu6Mo
# paSIq959/UZ163REVhc3f11eL4gy6nRRK54IUqRzJDSYbhWeHM6M+09ULc6WhBDr
# 1SyLNP95F5YaOrW7DZVdy54R/Ai/DGt7B6QhMLR/nSHBWWFmcY6DpJa2+QeK3PS5
# u0Ceuw+8J2QiwPahghcZMIIXFQYKKwYBBAGCNwMDATGCFwUwghcBBgkqhkiG9w0B
# BwKgghbyMIIW7gIBAzEPMA0GCWCGSAFlAwQCAQUAMIIBWQYLKoZIhvcNAQkQAQSg
# ggFIBIIBRDCCAUACAQEGCisGAQQBhFkKAwEwMTANBglghkgBZQMEAgEFAAQgB9Tr
# J0EwI6/b4YAd+RFSM2rX94WdnqDzUUC8/MukTAQCBmGVXfZF3hgTMjAyMTExMzAw
# NjQ5MzguMTIzWjAEgAIB9KCB2KSB1TCB0jELMAkGA1UEBhMCVVMxEzARBgNVBAgT
# Cldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29m
# dCBDb3Jwb3JhdGlvbjEtMCsGA1UECxMkTWljcm9zb2Z0IElyZWxhbmQgT3BlcmF0
# aW9ucyBMaW1pdGVkMSYwJAYDVQQLEx1UaGFsZXMgVFNTIEVTTjoxNzlFLTRCQjAt
# ODI0NjElMCMGA1UEAxMcTWljcm9zb2Z0IFRpbWUtU3RhbXAgU2VydmljZaCCEWgw
# ggcUMIIE/KADAgECAhMzAAABij44jdIOAvroAAEAAAGKMA0GCSqGSIb3DQEBCwUA
# MHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdS
# ZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xJjAkBgNVBAMT
# HU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEwMB4XDTIxMTAyODE5Mjc0MloX
# DTIzMDEyNjE5Mjc0MlowgdIxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5n
# dG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9y
# YXRpb24xLTArBgNVBAsTJE1pY3Jvc29mdCBJcmVsYW5kIE9wZXJhdGlvbnMgTGlt
# aXRlZDEmMCQGA1UECxMdVGhhbGVzIFRTUyBFU046MTc5RS00QkIwLTgyNDYxJTAj
# BgNVBAMTHE1pY3Jvc29mdCBUaW1lLVN0YW1wIFNlcnZpY2UwggIiMA0GCSqGSIb3
# DQEBAQUAA4ICDwAwggIKAoICAQC3/663oYMDIBm96AGFqBZ3QaipPyUUcx6mhY04
# s88QSgu7Jrhfef4rXgW+VnAWYrCpqnoH7oSQhNKOR5xNIHpBEDiSK90nJ2Uu8quD
# y520G7rssrKNCrBHMNBNGEQLGlTfS10ET8B7I/3mTuqd2Ei786lPhAbIYlSIwOWZ
# kCIM9jkUmSK1SAa/AwEfCiAnPwVUQEWdWIBRFMniQEOJTqmlu/g8j3v69CGmykMr
# 7zeBrJqJELeA1MbLeI6J7o+yXTdy9giIVwAlE/g7RGR4WW/9JCiibPcm2wx32ihL
# 9c7S9I32HYNUo40yNoU6Cc3lGTmIKrCafqqyZ76FqhH9OsIFLTNeNexZOCSWNQG2
# 3XtQFtbxEv70s3DdyM8nwRhGCUw1cJgszobMINcS8T1P/+wC/6TVzzi2aiJkNkGo
# GCv9K8v6BWw7PcSgNlDbqpNrVsSf+enEyZdy2hlJ7xJEOqArQlRaGMpeCfJo4AMQ
# H4W18iL6N1xQluk+0AviRa9VJEqKlW/wwS5hEt7FcQMQGL5Xi18oClmETiBrSn5A
# KJrAcsFk2iPdRA3MzlBWYZqLcydAVtmSGptQPKmj29pYR5V47fkl90taPBGC8xfd
# Upkvnt3uOZGOJWWW5eNkUvH6uEkvslhWm04+0XUwC0xiWno66Cc6kb7hbgwYeqPt
# hh8/RQIDAQABo4IBNjCCATIwHQYDVR0OBBYEFCPaQ9j9bBnUl66nSUeEPjGQaSQD
# MB8GA1UdIwQYMBaAFJ+nFV0AXmJdg/Tl0mWnG1M1GelyMF8GA1UdHwRYMFYwVKBS
# oFCGTmh0dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMvY3JsL01pY3Jvc29m
# dCUyMFRpbWUtU3RhbXAlMjBQQ0ElMjAyMDEwKDEpLmNybDBsBggrBgEFBQcBAQRg
# MF4wXAYIKwYBBQUHMAKGUGh0dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2lvcHMv
# Y2VydHMvTWljcm9zb2Z0JTIwVGltZS1TdGFtcCUyMFBDQSUyMDIwMTAoMSkuY3J0
# MAwGA1UdEwEB/wQCMAAwEwYDVR0lBAwwCgYIKwYBBQUHAwgwDQYJKoZIhvcNAQEL
# BQADggIBAMX0wRKw9cN5G18WjV/nvmI98X0BFZt66418znzch9PF/Nl/Z2/+Z7cM
# 2L8pw00SdHVMptm0bsuyDRzL+kogRA4kbZ9hpbAggpjC7IMkjZDiRWLmbNtX/QLn
# 69BCxBwK9+wzwrlfZ9+J8mLu2p4bSvnwKODB7vEFi+C4+aNQ3HBNa8SNkg9+mNVS
# ho8KXqqqzR4VRvttwuHNMQRgGcCPwwQ2GI/kgl3g+nmUWodO2l5zrtgWYa47+4gD
# 9OM8F9y0zmRQj67N/KH/Ih20M22QjP57/GZdIWGJARHS4GNGhtBlXpz7RM229E0t
# rJTi7sR6R3s5oNfNBHRG5YZpKLC03pdz8+g0/St7Mbo69zKjDWoyhSRQRDuqoPRC
# rxAXArQMoJ1lIm3IEowGmNRgKc1Rlti9NNabgNcrlFiB/bdtUElbhejnDj3Qcejh
# ONY2rPXs+o/IwJOczwdwCpOc94wTR09i9t3DMMyBu6bJ1slqr/ToUiaQnspez2PG
# oOITY9N5idqPzafpD/8+pse7HEmbBA7h/N06BWoASQbVcOamlUpb+snEE3cjHJWv
# pA/1yFjYxhVrRtsAIjZ29T5HZAmUTkCOgwrLrxYjWmYVPckoGutpynLodSMau1X7
# /VTnZuusSUKVXLkVvz5RlZkunzZy4LO0kwxKpb6Q/nPJUFK8sz7gMIIHcTCCBVmg
# AwIBAgITMwAAABXF52ueAptJmQAAAAAAFTANBgkqhkiG9w0BAQsFADCBiDELMAkG
# A1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQx
# HjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEyMDAGA1UEAxMpTWljcm9z
# b2Z0IFJvb3QgQ2VydGlmaWNhdGUgQXV0aG9yaXR5IDIwMTAwHhcNMjEwOTMwMTgy
# MjI1WhcNMzAwOTMwMTgzMjI1WjB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2Fz
# aGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENv
# cnBvcmF0aW9uMSYwJAYDVQQDEx1NaWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAx
# MDCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAOThpkzntHIhC3miy9ck
# eb0O1YLT/e6cBwfSqWxOdcjKNVf2AX9sSuDivbk+F2Az/1xPx2b3lVNxWuJ+Slr+
# uDZnhUYjDLWNE893MsAQGOhgfWpSg0S3po5GawcU88V29YZQ3MFEyHFcUTE3oAo4
# bo3t1w/YJlN8OWECesSq/XJprx2rrPY2vjUmZNqYO7oaezOtgFt+jBAcnVL+tuhi
# JdxqD89d9P6OU8/W7IVWTe/dvI2k45GPsjksUZzpcGkNyjYtcI4xyDUoveO0hyTD
# 4MmPfrVUj9z6BVWYbWg7mka97aSueik3rMvrg0XnRm7KMtXAhjBcTyziYrLNueKN
# iOSWrAFKu75xqRdbZ2De+JKRHh09/SDPc31BmkZ1zcRfNN0Sidb9pSB9fvzZnkXf
# tnIv231fgLrbqn427DZM9ituqBJR6L8FA6PRc6ZNN3SUHDSCD/AQ8rdHGO2n6Jl8
# P0zbr17C89XYcz1DTsEzOUyOArxCaC4Q6oRRRuLRvWoYWmEBc8pnol7XKHYC4jMY
# ctenIPDC+hIK12NvDMk2ZItboKaDIV1fMHSRlJTYuVD5C4lh8zYGNRiER9vcG9H9
# stQcxWv2XFJRXRLbJbqvUAV6bMURHXLvjflSxIUXk8A8FdsaN8cIFRg/eKtFtvUe
# h17aj54WcmnGrnu3tz5q4i6tAgMBAAGjggHdMIIB2TASBgkrBgEEAYI3FQEEBQID
# AQABMCMGCSsGAQQBgjcVAgQWBBQqp1L+ZMSavoKRPEY1Kc8Q/y8E7jAdBgNVHQ4E
# FgQUn6cVXQBeYl2D9OXSZacbUzUZ6XIwXAYDVR0gBFUwUzBRBgwrBgEEAYI3TIN9
# AQEwQTA/BggrBgEFBQcCARYzaHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3BraW9w
# cy9Eb2NzL1JlcG9zaXRvcnkuaHRtMBMGA1UdJQQMMAoGCCsGAQUFBwMIMBkGCSsG
# AQQBgjcUAgQMHgoAUwB1AGIAQwBBMAsGA1UdDwQEAwIBhjAPBgNVHRMBAf8EBTAD
# AQH/MB8GA1UdIwQYMBaAFNX2VsuP6KJcYmjRPZSQW9fOmhjEMFYGA1UdHwRPME0w
# S6BJoEeGRWh0dHA6Ly9jcmwubWljcm9zb2Z0LmNvbS9wa2kvY3JsL3Byb2R1Y3Rz
# L01pY1Jvb0NlckF1dF8yMDEwLTA2LTIzLmNybDBaBggrBgEFBQcBAQROMEwwSgYI
# KwYBBQUHMAKGPmh0dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9wa2kvY2VydHMvTWlj
# Um9vQ2VyQXV0XzIwMTAtMDYtMjMuY3J0MA0GCSqGSIb3DQEBCwUAA4ICAQCdVX38
# Kq3hLB9nATEkW+Geckv8qW/qXBS2Pk5HZHixBpOXPTEztTnXwnE2P9pkbHzQdTlt
# uw8x5MKP+2zRoZQYIu7pZmc6U03dmLq2HnjYNi6cqYJWAAOwBb6J6Gngugnue99q
# b74py27YP0h1AdkY3m2CDPVtI1TkeFN1JFe53Z/zjj3G82jfZfakVqr3lbYoVSfQ
# JL1AoL8ZthISEV09J+BAljis9/kpicO8F7BUhUKz/AyeixmJ5/ALaoHCgRlCGVJ1
# ijbCHcNhcy4sa3tuPywJeBTpkbKpW99Jo3QMvOyRgNI95ko+ZjtPu4b6MhrZlvSP
# 9pEB9s7GdP32THJvEKt1MMU0sHrYUP4KWN1APMdUbZ1jdEgssU5HLcEUBHG/ZPkk
# vnNtyo4JvbMBV0lUZNlz138eW0QBjloZkWsNn6Qo3GcZKCS6OEuabvshVGtqRRFH
# qfG3rsjoiV5PndLQTHa1V1QJsWkBRH58oWFsc/4Ku+xBZj1p/cvBQUl+fpO+y/g7
# 5LcVv7TOPqUxUYS8vwLBgqJ7Fx0ViY1w/ue10CgaiQuPNtq6TPmb/wrpNPgkNWcr
# 4A245oyZ1uEi6vAnQj0llOZ0dFtq0Z4+7X6gMTN9vMvpe784cETRkPHIqzqKOghi
# f9lwY1NNje6CbaUFEMFxBmoQtB1VM1izoXBm8qGCAtcwggJAAgEBMIIBAKGB2KSB
# 1TCB0jELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcT
# B1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEtMCsGA1UE
# CxMkTWljcm9zb2Z0IElyZWxhbmQgT3BlcmF0aW9ucyBMaW1pdGVkMSYwJAYDVQQL
# Ex1UaGFsZXMgVFNTIEVTTjoxNzlFLTRCQjAtODI0NjElMCMGA1UEAxMcTWljcm9z
# b2Z0IFRpbWUtU3RhbXAgU2VydmljZaIjCgEBMAcGBSsOAwIaAxUAgPDzY68bUwUE
# Haf/jB5WqnNXxKGggYMwgYCkfjB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2Fz
# aGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENv
# cnBvcmF0aW9uMSYwJAYDVQQDEx1NaWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAx
# MDANBgkqhkiG9w0BAQUFAAIFAOVPrjAwIhgPMjAyMTExMzAwMzUzMjBaGA8yMDIx
# MTIwMTAzNTMyMFowdzA9BgorBgEEAYRZCgQBMS8wLTAKAgUA5U+uMAIBADAKAgEA
# AgIaQwIB/zAHAgEAAgIRRTAKAgUA5VD/sAIBADA2BgorBgEEAYRZCgQCMSgwJjAM
# BgorBgEEAYRZCgMCoAowCAIBAAIDB6EgoQowCAIBAAIDAYagMA0GCSqGSIb3DQEB
# BQUAA4GBAFGs7y6NiUKwyEE1Z6cgj0+GtdScKR0oO66QBN+14/k7O3tvQnFo7+v4
# tn2OkXJBQdiEi1KKbVm6NGO42Ql2l/0MS8ZLqJgUq7so9Fc9+5ZO6bd1V8YPzGJD
# EGsIIFoVMS/zG+een6NwugI4jVqYezuA6inFAEZJnXfS+S/fTNArMYIEDTCCBAkC
# AQEwgZMwfDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNV
# BAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEmMCQG
# A1UEAxMdTWljcm9zb2Z0IFRpbWUtU3RhbXAgUENBIDIwMTACEzMAAAGKPjiN0g4C
# +ugAAQAAAYowDQYJYIZIAWUDBAIBBQCgggFKMBoGCSqGSIb3DQEJAzENBgsqhkiG
# 9w0BCRABBDAvBgkqhkiG9w0BCQQxIgQg58QiCvYzP0xjI+XxA5T1rBJD4RLFZuFW
# ywm8bJVqnbgwgfoGCyqGSIb3DQEJEAIvMYHqMIHnMIHkMIG9BCD0veCrdd9Kvn7z
# v38w+DG1kIUGhO0R5Dh+gJI5TVQpvTCBmDCBgKR+MHwxCzAJBgNVBAYTAlVTMRMw
# EQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVN
# aWNyb3NvZnQgQ29ycG9yYXRpb24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0
# YW1wIFBDQSAyMDEwAhMzAAABij44jdIOAvroAAEAAAGKMCIEIEMpiFzx4buOP+N+
# VFpeZth1IolYcPj8Oie0+ggsEzoZMA0GCSqGSIb3DQEBCwUABIICAKy5MZPu0HcD
# a6U/J6Mjh3c1+xDTavBY38OoanpYUPTzhX7zJWnhKQasGLG8XWzv4eJRTu5RRM9H
# mCOYCEIP0v+4I8K4c56mhVKB5+g7BSXJ5z8K9bmf4ELFhPWrnTxkZ9S0NdClhGm2
# 2QnmcqIJaCydxreMPQxIo8rDNar5oF4bQxWFWAdjODmQsWFlX7Ba87pgnQoZXWSJ
# gfnmAm1q3DYwxizD9dxTD6FqEM4mBkNCBoANqZcDlYytAtjivfxTxqD4GZul5oYW
# 3N/JsYb+uMZQRIKK8ws9eY5FxaC1VmIlc1v7tGW0Pg+2M96ggq4sAbAOi1TnP38A
# P4EehpS6bL2HtAhFVi2TlzoiX8UiLiPBfOxvC77kSvhN8FeiioIr4UqNc/O6ogCI
# 9xygDIHNZfub0Sg6UNtddD2Hv45V+oNbTQFHQlZhWHUceaoChQBMJXDtS5WIuEyc
# OjdSEmCR6svzH3bxEK/+vQPfsk4FGtjbZ9YEUeqT5r8mNulOhuNtNM4OL7fw8se5
# vL0OVqzNspSGj2dJB17E+gj17oTYd5lI1sexMErlzJQC4XQU6o2vgQxY+HIdG5lB
# UxgnZ7T5uzhF1BRqrTYCwnx7pF0bIfYf9ohQhXsjB0MMSdVnmOjHCcdYXCVnoi8O
# JnFuTEe+j3CWanuxi+5RiBRn4is+iV0z
# SIG # End signature block
