#
# Module manifest for module 'MicrosoftTeams'
#
# Generated by: Microsoft Corporation
#
# Updated on: 6/30/2020
#

@{
# Script module or binary module file associated with this manifest.
RootModule = './MicrosoftTeams.psm1'

# Version number of this module.
ModuleVersion = '2.6.0'

# Supported PSEditions
CompatiblePSEditions = 'Core', 'Desktop'

# ID used to uniquely identify this module
GUID = 'd910df43-3ca6-4c9c-a2e3-e9f45a8e2ad9'

# Author of this module
Author = 'Microsoft Corporation'

# Company or vendor of this module
CompanyName = 'Microsoft Corporation'

# Copyright statement for this module
Copyright = 'Microsoft Corporation. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Microsoft Teams cmdlets module for Windows PowerShell and PowerShell Core.

For more information, please visit the following: https://docs.microsoft.com/MicrosoftTeams/teams-powershell-overview'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
DotNetFrameworkVersion = '4.7.2'

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
CLRVersion = '4.0'

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = 'Amd64'

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
 ScriptsToProcess = @('.\SetMSTeamsReleaseEnvironment.ps1')

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = if($PSEdition -ne 'Desktop')
{
    '.\netcoreapp3.1\Microsoft.TeamsCmdlets.PowerShell.Connect.dll',
    '.\netcoreapp3.1\Microsoft.Teams.ConfigAPI.Cmdlets.psd1',
    '.\Microsoft.Teams.PowerShell.TeamsCmdlets.psd1'
}
else
{
    '.\net472\Microsoft.TeamsCmdlets.PowerShell.Connect.dll',
    '.\net472\Newtonsoft.Json.dll',
    '.\net472\Microsoft.Teams.ConfigAPI.Cmdlets.psd1',
    '.\Microsoft.Teams.PowerShell.TeamsCmdlets.psd1'
}

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport =  @(
   'Get-CsBatchPolicyAssignmentOperation'
   ,'Get-CsGroupPolicyAssignment'
   ,'Get-CsOnlinePowerShellEndpoint'
   ,'Get-CsPolicyPackage'
   ,'Get-CsUserPolicyAssignment'
   ,'Get-CsUserPolicyPackage'
   ,'Get-CsUserPolicyPackageRecommendation'
   ,'Grant-CsUserPolicyPackage'
   ,'New-CsBatchPolicyAssignmentOperation'
   ,'New-CsBatchPolicyPackageAssignmentOperation'
   ,'New-CsGroupPolicyAssignment'
   ,'Remove-CsGroupPolicyAssignment'
   ,'Move-CsInternalHelper'
   ,'Set-CsInternalOnlinePowerShellEndpoint'
   ,'Invoke-CsInternalPSTelemetry'
   ,'Grant-CsGroupPolicyPackageAssignment'
   ,'Get-CsTeamTemplateList'
   ,'Get-CsTeamTemplate'
   ,'Update-CsTeamTemplate'
   ,'New-CsTeamTemplate'
   ,'Remove-CsTeamTemplate'
   ,'New-CsCustomPolicyPackage'
   ,'Update-CsCustomPolicyPackage'
   ,'Remove-CsCustomPolicyPackage'
#Skype.TelephoneNumberMgmt Search V2
   ,'Get-CsOnlineTelephoneNumberCountry'
   ,'Get-CsOnlineTelephoneNumberType'
   ,'Get-CsOnlineTelephoneNumberOrder'
   ,'New-CsOnlineTelephoneNumberOrder'
   ,'Complete-CsOnlineTelephoneNumberOrder'
   ,'Clear-CsOnlineTelephoneNumberOrder'
#Audio File (autorest only)
   ,'Get-CsOnlineAudioFile'
   ,'Remove-CsOnlineAudioFile'
#Shift Connector
#preview    ,'Get-CsTeamsShiftsConnectionConnector'
#preview    ,'Test-CsTeamsShiftsConnectionValidate'
#preview    ,'New-CsTeamsShiftsConnectionInstance'
#preview    ,'Set-CsTeamsShiftsConnectionInstance'
#preview    ,'Remove-CsTeamsShiftsConnectionInstance'
#preview    ,'Get-CsTeamsShiftsConnectionInstance'
#preview    ,'Get-CsTeamsShiftsConnectionWfmTeam'
#preview    ,'New-CsTeamsShiftsConnectionTeamMap'
#preview    ,'Remove-CsTeamsShiftsConnectionTeamMap'
#preview    ,'Get-CsTeamsShiftsConnectionTeamMap'
#preview    ,'Get-CsTeamsShiftsConnectionSyncResult'
#preview    ,'Get-CsTeamsShiftsConnectionUser'
#SfBO: Begin
   ,'Clear-CsOnlineTelephoneNumberReservation'
   ,'ConvertTo-JsonForPSWS'
   ,'Disable-CsMeetingRoom'
   ,'Disable-CsOnlineDialInConferencingUser'
   ,'Disable-CsOnlineSipDomain'
   ,'Enable-CsMeetingRoom'
   ,'Enable-CsOnlineDialInConferencingUser'
   ,'Enable-CsOnlineSipDomain'
   ,'Export-CsAutoAttendantHolidays'
   ,'Export-CsOrganizationalAutoAttendantHolidays'
   ,'Find-CsGroup'
   ,'Find-CsOnlineApplicationInstance'
   ,'Get-CsApplicationAccessPolicy'
   ,'Get-CsApplicationMeetingConfiguration'
   ,'Get-CsAudioConferencingProvider'
   ,'Get-CsAutoAttendant'
   ,'Get-CsAutoAttendantHolidays'
   ,'Get-CsAutoAttendantStatus'
   ,'Get-CsAutoAttendantSupportedLanguage'
   ,'Get-CsAutoAttendantSupportedTimeZone'
   ,'Get-CsAutoAttendantTenantInformation'
   ,'Get-CsBroadcastMeetingConfiguration'
   ,'Get-CsBroadcastMeetingPolicy'
   ,'Get-CsCallingLineIdentity'
   ,'Get-CsCallQueue'
   ,'Get-CsClientPolicy'
   ,'Get-CsCloudCallDataConnection'
   ,'Get-CsCloudMeetingPolicy'
   ,'Get-CsConferencingPolicy'
   ,'Get-CsDefaultCatalogApp'
   ,'Get-CsDialPlan'
   ,'Get-CsEffectiveTenantDialPlan'
   ,'Get-CsExternalAccessPolicy'
   ,'Get-CsExternalUserCommunicationPolicy'
   ,'Get-CsGlobalCatalogApp'
   ,'Get-CsGraphPolicy'
   ,'Get-CsHostedVoicemailPolicy'
   ,'Get-CsHostingProvider'
   ,'Get-CsHuntGroup'
   ,'Get-CsHuntGroupTenantInformation'
   ,'Get-CsHybridMediationServer'
   ,'Get-CsHybridPSTNAppliance'
   ,'Get-CsHybridPSTNSite'
   ,'Get-CsImFilterConfiguration'
   ,'Get-CsInboundBlockedNumberPattern'
   ,'Get-CsInboundExemptNumberPattern'
   ,'Get-CsIPPhonePolicy'
   ,'Get-CsMeetingConfiguration'
   ,'Get-CsMeetingMigrationStatus'
   ,'Get-CsMeetingRoom'
   ,'Get-CsMobilityPolicy'
   ,'Get-CsNetworkConfiguration'
   ,'Get-CsOAuthConfiguration'
   ,'Get-CsOnlineApplicationEndpoint'
   ,'Get-CsOnlineApplicationInstance'
   ,'Get-CsOnlineApplicationInstanceAssociation'
   ,'Get-CsOnlineApplicationInstanceAssociationStatus'
   ,'Get-CsOnlineAudioConferencingRoutingPolicy'
   ,'Get-CsOnlineDialInConferencingBridge'
   ,'Get-CsOnlineDialInConferencingLanguagesSupported'
   ,'Get-CsOnlineDialinConferencingPolicy'
   ,'Get-CsOnlineDialInConferencingServiceNumber'
   ,'Get-CsOnlineDialinConferencingTenantConfiguration'
   ,'Get-CsOnlineDialInConferencingTenantSettings'
   ,'Get-CsOnlineDialInConferencingUser'
   ,'Get-CsOnlineDialInConferencingUserInfo'
   ,'Get-CsOnlineDialInConferencingUserState'
   ,'Get-CsOnlineDialOutPolicy'
   ,'Get-CsOnlineDirectoryTenant'
   ,'Get-CsOnlineDirectoryTenantNumberCities'
   ,'Get-CsOnlineEnhancedEmergencyServiceDisclaimer'
   ,'Get-CsOnlineLisCivicAddress'
   ,'Get-CsOnlineLisLocation'
   ,'Get-CsOnlineLisPort'
   ,'Get-CsOnlineLisSubnet'
   ,'Get-CsOnlineLisSwitch'
   ,'Get-CsOnlineLisWirelessAccessPoint'
   ,'Get-CsOnlineNumberPortInOrder'
   ,'Get-CsOnlineNumberPortOutOrderPin'
   ,'Get-CsOnlinePSTNGateway'
   ,'Get-CsOnlinePstnUsage'
   ,'Get-CsOnlineSchedule'
   ,'Get-CsOnlineSipDomain'
   ,'Get-CsOnlineTelephoneNumber'
   ,'Get-CsOnlineTelephoneNumberAvailableCount'
   ,'Get-CsOnlineTelephoneNumberInventoryAreas'
   ,'Get-CsOnlineTelephoneNumberInventoryCities'
   ,'Get-CsOnlineTelephoneNumberInventoryCountries'
   ,'Get-CsOnlineTelephoneNumberInventoryRegions'
   ,'Get-CsOnlineTelephoneNumberInventoryTypes'
   ,'Get-CsOnlineTelephoneNumberReservationsInformation'
   ,'Get-CsOnlineUser'
   ,'Get-CsOnlineVoicemailPolicy'
   ,'Get-CsOnlineVoicemailUserSettings'
   ,'Get-CsOnlineVoiceRoute'
   ,'Get-CsOnlineVoiceRoutingPolicy'
   ,'Get-CsOnlineVoiceUser'
   ,'Get-CsOrganizationalAutoAttendant'
   ,'Get-CsOrganizationalAutoAttendantHolidays'
   ,'Get-CsOrganizationalAutoAttendantStatus'
   ,'Get-CsOrganizationalAutoAttendantSupportedLanguage'
   ,'Get-CsOrganizationalAutoAttendantSupportedTimeZone'
   ,'Get-CsOrganizationalAutoAttendantTenantInformation'
   ,'Get-CsPresencePolicy'
   ,'Get-CsPrivacyConfiguration'
   ,'Get-CsPushNotificationConfiguration'
   ,'Get-CsTeamsAcsFederationConfiguration'
   ,'Get-CsTeamsAppPermissionPolicy'
   ,'Get-CsTeamsAppPreset'
   ,'Get-CsTeamsAppSetupPolicy'
   ,'Get-CsTeamsAudioConferencingPolicy'
   ,'Get-CsTeamsCallingPolicy'
   ,'Get-CsTeamsCallParkPolicy'
   ,'Get-CsTeamsCallHoldPolicy'
   ,'Get-CsTeamsChannelsPolicy'
   ,'Get-CsTeamsClientConfiguration'
   ,'Get-CsTeamsComplianceRecordingApplication'
   ,'Get-CsTeamsComplianceRecordingPolicy'
   ,'Get-CsTeamsCortanaPolicy'
   ,'Get-CsTeamsEducationAssignmentsAppPolicy'
   ,'Get-CsTeamsEmergencyCallingPolicy'
   ,'Get-CsTeamsEmergencyCallRoutingPolicy'
   ,'Get-CsTeamsFeedbackPolicy'
   ,'Get-CsTeamsGuestCallingConfiguration'
   ,'Get-CsTeamsGuestMeetingConfiguration'
   ,'Get-CsTeamsGuestMessagingConfiguration'
   ,'Get-CsTeamsIPPhonePolicy'
   ,'Get-CsTeamsMeetingBroadcastConfiguration'
   ,'Get-CsTeamsMeetingBroadcastPolicy'
   ,'Get-CsTeamsMeetingConfiguration'
   ,'Get-CsTeamsMeetingPolicy'
   ,'Get-CsTeamsMessagingPolicy'
   ,'Get-CsTeamsMigrationConfiguration'
   ,'Get-CsTeamsMobilityPolicy'
   ,'Get-CsTeamsNetworkRoamingPolicy'
   ,'Get-CsTeamsNotificationAndFeedsPolicy'
   ,'Get-CsTeamsPinnedApp'
   ,'Get-CsTeamsShiftsAppPolicy'
   ,'Get-CsTeamsShiftsPolicy'
   ,'Get-CsTeamsSurvivableBranchAppliance'
   ,'Get-CsTeamsSurvivableBranchAppliancePolicy'
   ,'Get-CsTeamsTargetingPolicy'
   ,'Get-CsTeamsTranslationRule'
   ,'Get-CsTeamsUpdateManagementPolicy'
   ,'Get-CsTeamsUpgradeConfiguration'
   ,'Get-CsTeamsUpgradePolicy'
   ,'Get-CsTeamsUpgradeStatus'
   ,'Get-CsTeamsVdiPolicy'
   ,'Get-CsTeamsVerticalPackagePolicy'
   ,'Get-CsTeamsVideoInteropServicePolicy'
   ,'Get-CsTeamsWorkLoadPolicy'
   ,'Get-CsTenant'
   ,'Get-CsTenantBlockedCallingNumbers'
   ,'Get-CsTeamsEnhancedEncryptionPolicy'
   ,'Get-CsTenantCatalogApp'
   ,'Get-CsTenantDialPlan'
   ,'Get-CsTenantFederationConfiguration'
   ,'Get-CsTenantHybridConfiguration'
   ,'Get-CsTenantLicensingConfiguration'
   ,'Get-CsTenantMigrationConfiguration'
   ,'Get-CsTenantNetworkConfiguration'
   ,'Get-CsTenantNetworkPostalCode'
   ,'Get-CsTenantNetworkRegion'
   ,'Get-CsTenantNetworkSite'
   ,'Get-CsTenantNetworkSubnet'
   ,'Get-CsTenantPublicProvider'
   ,'Get-CsTenantTrustedIPAddress'
   ,'Get-CsTenantUpdateTimeWindow'
   ,'Get-CsUCPhoneConfiguration'
   ,'Get-CsUserAcp'
   ,'Get-CsUserLocationStatus'
   ,'Get-CsUserPstnSettings'
   ,'Get-CsUserServicesPolicy'
   ,'Get-CsVideoInteropServiceProvider'
   ,'Get-CsVoiceNormalizationRule'
   ,'Get-CsVoiceRoutingPolicy'
   ,'Get-CsTeamsUnassignedNumberTreatment'
   ,'Grant-CsApplicationAccessPolicy'
   ,'Grant-CsBroadcastMeetingPolicy'
   ,'Grant-CsCallingLineIdentity'
   ,'Grant-CsClientPolicy'
   ,'Grant-CsCloudMeetingPolicy'
   ,'Grant-CsConferencingPolicy'
   ,'Grant-CsDialoutPolicy'
   ,'Grant-CsExternalAccessPolicy'
   ,'Grant-CsExternalUserCommunicationPolicy'
   ,'Grant-CsGraphPolicy'
   ,'Grant-CsHostedVoicemailPolicy'
   ,'Grant-CsIPPhonePolicy'
   ,'Grant-CsMobilityPolicy'
   ,'Grant-CsOnlineAudioConferencingRoutingPolicy'
   ,'Grant-CsOnlineVoicemailPolicy'
   ,'Grant-CsOnlineVoiceRoutingPolicy'
   ,'Grant-CsPolicy'
   ,'Grant-CsTeamsAppPermissionPolicy'
   ,'Grant-CsTeamsAppSetupPolicy'
   ,'Grant-CsTeamsAudioConferencingPolicy'
   ,'Grant-CsTeamsCallingPolicy'
   ,'Grant-CsTeamsCallParkPolicy'
   ,'Grant-CsTeamsCallHoldPolicy'
   ,'Grant-CsTeamsChannelsPolicy'
   ,'Grant-CsTeamsComplianceRecordingPolicy'
   ,'Grant-CsTeamsCortanaPolicy'
   ,'Grant-CsTeamsEmergencyCallingPolicy'
   ,'Grant-CsTeamsEmergencyCallRoutingPolicy'
   ,'Grant-CsTeamsFeedbackPolicy'
   ,'Grant-CsTeamsIPPhonePolicy'
   ,'Grant-CsTeamsMeetingBroadcastPolicy'
   ,'Grant-CsTeamsMeetingPolicy'
   ,'Grant-CsTeamsMessagingPolicy'
   ,'Grant-CsTeamsMobilityPolicy'
   ,'Grant-CsTeamsShiftsPolicy'
   ,'Grant-CsTeamsSurvivableBranchAppliancePolicy'
   ,'Grant-CsTeamsUpdateManagementPolicy'
   ,'Grant-CsTeamsUpgradePolicy'
   ,'Grant-CsTeamsVdiPolicy'
   ,'Grant-CsTeamsVerticalPackagePolicy'
   ,'Grant-CsTeamsVideoInteropServicePolicy'
   ,'Grant-CsTeamsWorkLoadPolicy'
   ,'Grant-CsTenantDialPlan'
   ,'Grant-CsVoiceRoutingPolicy'
   ,'Grant-CsTeamsEnhancedEncryptionPolicy'
   ,'Import-CsAutoAttendantHolidays'
   ,'Import-CsOnlineAudioFile'
   ,'Import-CsOrganizationalAutoAttendantHolidays'
   ,'Invoke-CsUcsRollback'
   ,'Invoke-CsUserPreferredDataLocationSync'
   ,'New-CsApplicationAccessPolicy'
   ,'New-CsAutoAttendant'
   ,'New-CsAutoAttendantCallableEntity'
   ,'New-CsAutoAttendantCallFlow'
   ,'New-CsAutoAttendantCallHandlingAssociation'
   ,'New-CsAutoAttendantDialScope'
   ,'New-CsAutoAttendantMenu'
   ,'New-CsAutoAttendantMenuOption'
   ,'New-CsAutoAttendantPrompt'
   ,'New-CsCallingLineIdentity'
   ,'New-CsCallQueue'
   ,'New-CsClientPolicy'
   ,'New-CsCloudCallDataConnection'
   ,'New-CsConferencingPolicy'
   ,'New-CsDefaultCatalogApp'
   ,'New-CsEdgeAllowAllKnownDomains'
   ,'New-CsEdgeAllowList'
   ,'New-CsEdgeDomainPattern'
   ,'New-CsExternalAccessPolicy'
   ,'New-CsExternalUserCommunicationPolicy'
   ,'New-CsGlobalCatalogApp'
   ,'New-CsHuntGroup'
   ,'New-CsHybridPSTNSite'
   ,'New-CsHybridTelephoneNumber'
   ,'New-CsInboundBlockedNumberPattern'
   ,'New-CsInboundExemptNumberPattern'
   ,'New-CsMobilityPolicy'
   ,'New-CsNetworkMediaBypassConfiguration'
   ,'New-CsOnlineApplicationEndpoint'
   ,'New-CsOnlineApplicationInstance'
   ,'New-CsOnlineApplicationInstanceAssociation'
   ,'New-CsOnlineAudioConferencingRoutingPolicy'
   ,'New-CsOnlineAudioFile'
   ,'New-CsOnlineBulkAssignmentInput'
   ,'New-CsOnlineDateTimeRange'
   ,'New-CsOnlineLisCivicAddress'
   ,'New-CsOnlineLisLocation'
   ,'New-CsOnlineNumberPortInOrder'
   ,'New-CsOnlinePSTNGateway'
   ,'New-CsOnlineSchedule'
   ,'New-CsOnlineTimeRange'
   ,'New-CsOnlineVoicemailPolicy'
   ,'New-CsOnlineVoiceRoute'
   ,'New-CsOnlineVoiceRoutingPolicy'
   ,'New-CsOrganizationalAutoAttendant'
   ,'New-CsOrganizationalAutoAttendantCallableEntity'
   ,'New-CsOrganizationalAutoAttendantCallFlow'
   ,'New-CsOrganizationalAutoAttendantCallHandlingAssociation'
   ,'New-CsOrganizationalAutoAttendantDialScope'
   ,'New-CsOrganizationalAutoAttendantMenu'
   ,'New-CsOrganizationalAutoAttendantMenuOption'
   ,'New-CsOrganizationalAutoAttendantPrompt'
   ,'New-CsTeamsAppPermissionPolicy'
   ,'New-CsTeamsAppPreset'
   ,'New-CsTeamsAppSetupPolicy'
   ,'New-CsTeamsAudioConferencingPolicy'
   ,'New-CsTeamsCallingPolicy'
   ,'New-CsTeamsCallParkPolicy'
   ,'New-CsTeamsCallHoldPolicy'
   ,'New-CsTeamsChannelsPolicy'
   ,'New-CsTeamsComplianceRecordingApplication'
   ,'New-CsTeamsComplianceRecordingPairedApplication'
   ,'New-CsTeamsComplianceRecordingPolicy'
   ,'New-CsTeamsCortanaPolicy'
   ,'New-CsTeamsEmergencyCallingPolicy'
   ,'New-CsTeamsEmergencyCallRoutingPolicy'
   ,'New-CsTeamsEmergencyNumber'
   ,'New-CsTeamsFeedbackPolicy'
   ,'New-CsTeamsIPPhonePolicy'
   ,'New-CsTeamsMeetingBroadcastPolicy'
   ,'New-CsTeamsMeetingPolicy'
   ,'New-CsTeamsMessagingPolicy'
   ,'New-CsTeamsMobilityPolicy'
   ,'New-CsTeamsNetworkRoamingPolicy'
   ,'New-CsTeamsPinnedApp'
   ,'New-CsTeamsShiftsPolicy'
   ,'New-CsTeamsSurvivableBranchAppliance'
   ,'New-CsTeamsSurvivableBranchAppliancePolicy'
   ,'New-CsTeamsTranslationRule'
   ,'New-CsTeamsUpdateManagementPolicy'
   ,'New-CsTeamsVdiPolicy'
   ,'New-CsTeamsVerticalPackagePolicy'
   ,'New-CsTeamsWorkLoadPolicy'
   ,'New-CsTeamsEnhancedEncryptionPolicy'
   ,'New-CsTenantCatalogApp'
   ,'New-CsTenantDialPlan'
   ,'New-CsTenantNetworkPostalCode'
   ,'New-CsTenantNetworkRegion'
   ,'New-CsTenantNetworkSite'
   ,'New-CsTenantNetworkSubnet'
   ,'New-CsTenantTrustedIPAddress'
   ,'New-CsTenantUpdateTimeWindow'
   ,'New-CsVideoInteropServiceProvider'
   ,'New-CsVoiceNormalizationRule'
   ,'New-CsTeamsUnassignedNumberTreatment'
   ,'Register-CsHybridPSTNAppliance'
   ,'Register-CsOnlineDialInConferencingServiceNumber'
   ,'Remove-CsApplicationAccessPolicy'
   ,'Remove-CsAutoAttendant'
   ,'Remove-CsCallingLineIdentity'
   ,'Remove-CsCallQueue'
   ,'Remove-CsClientPolicy'
   ,'Remove-CsConferencingPolicy'
   ,'Remove-CsDefaultCatalogApp'
   ,'Remove-CsExternalAccessPolicy'
   ,'Remove-CsExternalUserCommunicationPolicy'
   ,'Remove-CsGlobalCatalogApp'
   ,'Remove-CsHuntGroup'
   ,'Remove-CsHybridPSTNSite'
   ,'Remove-CsHybridTelephoneNumber'
   ,'Remove-CsInboundBlockedNumberPattern'
   ,'Remove-CsInboundExemptNumberPattern'
   ,'Remove-CsMobilityPolicy'
   ,'Remove-CsOnlineApplicationEndpoint'
   ,'Remove-CsOnlineApplicationInstanceAssociation'
   ,'Remove-CsOnlineAudioConferencingRoutingPolicy'
   ,'Remove-CsOnlineDialInConferencingTenantSettings'
   ,'Remove-CsOnlineLisCivicAddress'
   ,'Remove-CsOnlineLisLocation'
   ,'Remove-CsOnlineLisPort'
   ,'Remove-CsOnlineLisSubnet'
   ,'Remove-CsOnlineLisSwitch'
   ,'Remove-CsOnlineLisWirelessAccessPoint'
   ,'Remove-CsOnlineNumberPortInOrder'
   ,'Remove-CsOnlinePSTNGateway'
   ,'Remove-CsOnlineSchedule'
   ,'Remove-CsOnlineTelephoneNumber'
   ,'Remove-CsOnlineVoicemailPolicy'
   ,'Remove-CsOnlineVoiceRoute'
   ,'Remove-CsOnlineVoiceRoutingPolicy'
   ,'Remove-CsOrganizationalAutoAttendant'
   ,'Remove-CsTeamsAppPermissionPolicy'
   ,'Remove-CsTeamsAppPreset'
   ,'Remove-CsTeamsAppSetupPolicy'
   ,'Remove-CsTeamsAudioConferencingPolicy'
   ,'Remove-CsTeamsCallingPolicy'
   ,'Remove-CsTeamsCallParkPolicy'
   ,'Remove-CsTeamsCallHoldPolicy'
   ,'Remove-CsTeamsChannelsPolicy'
   ,'Remove-CsTeamsComplianceRecordingApplication'
   ,'Remove-CsTeamsComplianceRecordingPolicy'
   ,'Remove-CsTeamsCortanaPolicy'
   ,'Remove-CsTeamsEmergencyCallingPolicy'
   ,'Remove-CsTeamsEmergencyCallRoutingPolicy'
   ,'Remove-CsTeamsFeedbackPolicy'
   ,'Remove-CsTeamsIPPhonePolicy'
   ,'Remove-CsTeamsMeetingBroadcastPolicy'
   ,'Remove-CsTeamsMeetingPolicy'
   ,'Remove-CsTeamsMessagingPolicy'
   ,'Remove-CsTeamsMobilityPolicy'
   ,'Remove-CsTeamsNetworkRoamingPolicy'
   ,'Remove-CsTeamsNotificationAndFeedsPolicy'
   ,'Remove-CsTeamsPinnedApp'
   ,'Remove-CsTeamsShiftsPolicy'
   ,'Remove-CsTeamsSurvivableBranchAppliance'
   ,'Remove-CsTeamsSurvivableBranchAppliancePolicy'
   ,'Remove-CsTeamsTargetingPolicy'
   ,'Remove-CsTeamsTranslationRule'
   ,'Remove-CsTeamsUpdateManagementPolicy'
   ,'Remove-CsTeamsVdiPolicy'
   ,'Remove-CsTeamsVerticalPackagePolicy'
   ,'Remove-CsTeamsWorkLoadPolicy'
   ,'Remove-CsTeamsEnhancedEncryptionPolicy'
   ,'Remove-CsTenantCatalogApp'
   ,'Remove-CsTenantDialPlan'
   ,'Remove-CsTenantNetworkConfiguration'
   ,'Remove-CsTenantNetworkPostalCode'
   ,'Remove-CsTenantNetworkRegion'
   ,'Remove-CsTenantNetworkSite'
   ,'Remove-CsTenantNetworkSubnet'
   ,'Remove-CsTenantTrustedIPAddress'
   ,'Remove-CsTenantUpdateTimeWindow'
   ,'Remove-CsUserAcp'
   ,'Remove-CsVideoInteropServiceProvider'
   ,'Remove-CsVoiceNormalizationRule'
   ,'Remove-CsTeamsUnassignedNumberTreatment'
   ,'Search-CsOnlineTelephoneNumberInventory'
   ,'Select-CsOnlineTelephoneNumberInventory'
   ,'Set-CsApplicationAccessPolicy'
   ,'Set-CsApplicationMeetingConfiguration'
   ,'Set-CsAutoAttendant'
   ,'Set-CsBroadcastMeetingConfiguration'
   ,'Set-CsCallingLineIdentity'
   ,'Set-CsCallQueue'
   ,'Set-CsCceApplianceConfigurationReplicationStatus'
   ,'Set-CsCceApplianceDeploymentStatus'
   ,'Set-CsCceApplianceStatus'
   ,'Set-CsClientPolicy'
   ,'Set-CsConferencingPolicy'
   ,'Set-CsDefaultCatalogApp'
   ,'Set-CsExternalAccessPolicy'
   ,'Set-CsExternalUserCommunicationPolicy'
   ,'Set-CsGlobalCatalogApp'
   ,'Set-CsHuntGroup'
   ,'Set-CsHybridMediationServer'
   ,'Set-CsHybridPSTNAppliance'
   ,'Set-CsHybridPSTNSite'
   ,'Set-CsInboundBlockedNumberPattern'
   ,'Set-CsInboundExemptNumberPattern'
   ,'Set-CsIPPhonePolicy'
   ,'Set-CsMeetingConfiguration'
   ,'Set-CsMeetingRoom'
   ,'Set-CsMobilityPolicy'
   ,'Set-CsNetworkConfiguration'
   ,'Set-CsOAuthConfiguration'
   ,'Set-CsOnlineApplicationEndpoint'
   ,'Set-CsOnlineApplicationInstance'
   ,'Set-CsOnlineAudioConferencingRoutingPolicy'
   ,'Set-CsOnlineDialInConferencingBridge'
   ,'Set-CsOnlineDialInConferencingServiceNumber'
   ,'Set-CsOnlineDialInConferencingTenantSettings'
   ,'Set-CsOnlineDialInConferencingUser'
   ,'Set-CsOnlineDialInConferencingUserDefaultNumber'
   ,'Set-CsOnlineDirectoryUser'
   ,'Set-CsOnlineEnhancedEmergencyServiceDisclaimer'
   ,'Set-CsOnlineLisCivicAddress'
   ,'Set-CsOnlineLisLocation'
   ,'Set-CsOnlineLisPort'
   ,'Set-CsOnlineLisSubnet'
   ,'Set-CsOnlineLisSwitch'
   ,'Set-CsOnlineLisWirelessAccessPoint'
   ,'Set-CsOnlineNumberPortInOrder'
   ,'Set-CsOnlineNumberPortOutOrderPin'
   ,'Set-CsOnlinePSTNGateway'
   ,'Set-CsOnlinePstnUsage'
   ,'Set-CsOnlineSchedule'
   ,'Set-CsOnlineVoiceApplicationInstance'
   ,'Set-CsOnlineVoicemailPolicy'
   ,'Set-CsOnlineVoicemailUserSettings'
   ,'Set-CsOnlineVoiceRoute'
   ,'Set-CsOnlineVoiceRoutingPolicy'
   ,'Set-CsOnlineVoiceUser'
   ,'Set-CsOnlineVoiceUserBulk'
   ,'Set-CsOrganizationalAutoAttendant'
   ,'Set-CsPrivacyConfiguration'
   ,'Set-CsPushNotificationConfiguration'
   ,'Set-CsTeamsAcsFederationConfiguration'
   ,'Set-CsTeamsAppPermissionPolicy'
   ,'Set-CsTeamsAppPreset'
   ,'Set-CsTeamsAppSetupPolicy'
   ,'Set-CsTeamsAudioConferencingPolicy'
   ,'Set-CsTeamsCallingPolicy'
   ,'Set-CsTeamsCallParkPolicy'
   ,'Set-CsTeamsCallHoldPolicy'
   ,'Set-CsTeamsChannelsPolicy'
   ,'Set-CsTeamsClientConfiguration'
   ,'Set-CsTeamsComplianceRecordingApplication'
   ,'Set-CsTeamsComplianceRecordingPolicy'
   ,'Set-CsTeamsCortanaPolicy'
   ,'Set-CsTeamsEducationAssignmentsAppPolicy'
   ,'Set-CsTeamsEmergencyCallingPolicy'
   ,'Set-CsTeamsEmergencyCallRoutingPolicy'
   ,'Set-CsTeamsFeedbackPolicy'
   ,'Set-CsTeamsGuestCallingConfiguration'
   ,'Set-CsTeamsGuestMeetingConfiguration'
   ,'Set-CsTeamsGuestMessagingConfiguration'
   ,'Set-CsTeamsIPPhonePolicy'
   ,'Set-CsTeamsMeetingBroadcastConfiguration'
   ,'Set-CsTeamsMeetingBroadcastPolicy'
   ,'Set-CsTeamsMeetingConfiguration'
   ,'Set-CsTeamsMeetingPolicy'
   ,'Set-CsTeamsMessagingPolicy'
   ,'Set-CsTeamsMigrationConfiguration'
   ,'Set-CsTeamsMobilityPolicy'
   ,'Set-CsTeamsNetworkRoamingPolicy'
   ,'Set-CsTeamsNotificationAndFeedsPolicy'
   ,'Set-CsTeamsPinnedApp'
   ,'Set-CsTeamsShiftsAppPolicy'
   ,'Set-CsTeamsShiftsPolicy'
   ,'Set-CsTeamsSurvivableBranchAppliance'
   ,'Set-CsTeamsSurvivableBranchAppliancePolicy'
   ,'Set-CsTeamsTargetingPolicy'
   ,'Set-CsTeamsTranslationRule'
   ,'Set-CsTeamsUpdateManagementPolicy'
   ,'Set-CsTeamsUpgradeConfiguration'
   ,'Set-CsTeamsUpgradeStatus'
   ,'Set-CsTeamsVdiPolicy'
   ,'Set-CsTeamsVerticalPackagePolicy'
   ,'Set-CsTeamsWorkLoadPolicy'
   ,'Set-CsTenantBlockedCallingNumbers'
   ,'Set-CsTeamsEnhancedEncryptionPolicy'
   ,'Set-CsTenantCatalogApp'
   ,'Set-CsTenantDialPlan'
   ,'Set-CsTenantFederationConfiguration'
   ,'Set-CsTenantHybridConfiguration'
   ,'Set-CsTenantMigrationConfiguration'
   ,'Set-CsTenantNetworkConfiguration'
   ,'Set-CsTenantNetworkPostalCode'
   ,'Set-CsTenantNetworkRegion'
   ,'Set-CsTenantNetworkSite'
   ,'Set-CsTenantNetworkSubnet'
   ,'Set-CsTenantPublicProvider'
   ,'Set-CsTenantTrustedIPAddress'
   ,'Set-CsTenantUpdateTimeWindow'
   ,'Set-CsUCPhoneConfiguration'
   ,'Set-CsUser'
   ,'Set-CsUserAcp'
   ,'Set-CsUserPstnSettings'
   ,'Set-CsUserServicesPolicy'
   ,'Set-CsVideoInteropServiceProvider'
   ,'Set-CsVoiceNormalizationRule'
   ,'Set-CsTeamsUnassignedNumberTreatment'
   ,'Start-CsExMeetingMigration'
   ,'Switch-CsOnlineApplicationEndpoint'
   ,'Sync-CsOnlineApplicationInstance'
   ,'Test-CsEffectiveTenantDialPlan'
   ,'Test-CsInboundBlockedNumberPattern'
   ,'Test-CsOnlineCarrierPortabilityIn'
   ,'Test-CsOnlineLisCivicAddress'
   ,'Test-CsOnlinePortabilityIn'
   ,'Test-CsVoiceNormalizationRule'
   ,'Unregister-CsHybridPSTNAppliance'
   ,'Unregister-CsOnlineDialInConferencingServiceNumber'
   ,'Update-CsAutoAttendant'
   ,'Update-CsOrganizationalAutoAttendant'
   ,'Update-CsTenantMeetingUrl'
#SfBO: End
)
# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @(
    'Add-TeamUser'
    ,'Connect-MicrosoftTeams'
    ,'Disconnect-MicrosoftTeams'
    ,'Get-MultiGeoRegion'
    ,'Get-Operation'
    ,'Get-Team'
    ,'Get-TeamChannel'
    ,'Get-TeamsApp'
    ,'Get-TeamUser'
    ,'New-Team'
    ,'New-TeamChannel'
    ,'New-TeamsApp'
    ,'Remove-Team'
    ,'Remove-TeamChannel'
    ,'Remove-TeamsApp'
    ,'Remove-TeamUser'
    ,'Set-Team'
    ,'Set-TeamArchivedState'
    ,'Set-TeamChannel'
    ,'Set-TeamPicture'
    ,'Set-TeamsApp'
#preview    ,'Add-TeamChannelUser'
#preview    ,'Add-TeamsAppInstallation'
#preview    ,'Get-TeamChannelUser'
#preview    ,'Get-TeamsAppInstallation'
#preview    ,'Get-TeamTargetingHierarchyStatus'
#preview    ,'Remove-TeamChannelUser'
#preview    ,'Remove-TeamsAppInstallation'
#preview    ,'Remove-TeamTargetingHierarchy'
#preview    ,'Set-TeamTargetingHierarchy'
#preview    ,'Update-TeamsAppInstallation'
#preview    ,'Get-LicenseReportForChangeNotificationSubscription'
 )

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = '*'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{
    PSData = @{
        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Office365', 'MicrosoftTeams', 'Teams'

        # A URL to the license for this module.
        LicenseUri = 'https://raw.githubusercontent.com/MicrosoftDocs/office-docs-powershell/master/teams/LICENSE.txt'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/MicrosoftDocs/office-docs-powershell/tree/master/teams'

        # A URL to an icon representing this module.
        IconUri = 'https://statics.teams.microsoft.com/evergreen-assets/apps/teamscmdlets_largeimage.png'

        # Appends prerelease string to version
        Prerelease = ''

        # ReleaseNotes of this module
        ReleaseNotes = @'
 **2.6.0-GA** (The project - MicrosoftTeams contains these changes so far for this release)

- Releases [Get|Set|Grant|New|Remove]-CsTeamsEnhancedEncryptionPolicy cmdlets.
- Removes [Get|Set|New|Remove]-CsTenantBlockedNumberExceptionPattern cmdlets.
- Fixes the bug where MicrosoftTeams module lookup failed if made a nested module of another custom PowerShell module. Now, MicrosoftTeams cmdlets are available even if its a nested module of another module.
- Releases [Get|New|Complete|Clear]-CsOnlineTelephoneNumberOrder cmdlets.
- Releases Get-CsOnlineTelephoneNumberCountry, Get-CsOnlineTelephoneNumberType cmdlets.
- Releases new parameters for these cmdlets - Get-CsOnlineApplicationInstance, New-CsExternalAccessPolicy, New-CsTeamsAppSetupPolicy,
  New-CsTeamsCallingPolicy, New-CsTeamsCallParkPolicy, New-CsTeamsMeetingPolicy, New-CsTeamsMessagingPolicy, Set-CsTeamsAppSetupPolicy, Set-CsTeamsCallParkPolicy,
  Set-CsTeamsGuestMessagingConfiguration, Set-CsTeamsMeetingPolicy, Set-CsTenantFederationConfiguration, Set-CsExternalAccessPolicy, Set-CsTeamsCallingPolicy
- Fixes the failure that occured when retrying login with Connect-MicrosoftTeams after an incorrect sign-in attempt.
- Fixes Add-TeamChannelUser and Remove-TeamChannelUser failing for private channel.
- Changes done to make released module's release notes to be available in PowerShell Gallery.
- The complete release notes can be found in the below link:
https://docs.microsoft.com/MicrosoftTeams/teams-powershell-release-notes
'@
    } # End of PSData hashtable
} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''
}

# SIG # Begin signature block
# MIIjcAYJKoZIhvcNAQcCoIIjYTCCI10CAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCC3V1eH215qtt5B
# D7oZ5fqjmOpRgxXj/rluUln/PzqST6CCDXMwggXxMIID2aADAgECAhMzAAACGYwK
# n7IWKxDmAAAAAAIZMA0GCSqGSIb3DQEBCwUAMH4xCzAJBgNVBAYTAlVTMRMwEQYD
# VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNpZ25p
# bmcgUENBIDIwMTEwHhcNMjEwNDI5MTkxMjU1WhcNMjIwNDI4MTkxMjU1WjByMQsw
# CQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9u
# ZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMRwwGgYDVQQDExNTa3lw
# ZSBTb2Z0d2FyZSBTYXJsMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
# nxMscK0w8ebaayvQhxPtLTkomfivSX4yNLmQJGXG+1yUKU4fmdQAhZm5mSIdFAEv
# sjAwCP3vUmh2N5R5TrAN/whfjGcDDlCYonKcrmuSaXxGuyjXKlELlRmPOaobqeo1
# 1Amcz6SRbNYBtKtRiP5ip2PfAvtJp7AvH0mZfGXKehE4C+5t8XYZ3K1JU3Tdb+3Z
# z+smovI8h/ZPe+uV2ORTxxa9kBLDvueJZbzKkn/WAIX/8rq/ywHtffSTXSueUmoe
# NJ0UCyoNBr90xtnozaCVknyRG8qWzHEZlc43FPNwIW6y8k1JSuspq+SML/HP7Fjv
# 7zcTLtM1HBBX/I9KxBJSBQIDAQABo4IBcjCCAW4wEwYDVR0lBAwwCgYIKwYBBQUH
# AwMwHQYDVR0OBBYEFAZqNYGuvWVnCVhV5aJBAvx4cJdwMFAGA1UdEQRJMEekRTBD
# MSkwJwYDVQQLEyBNaWNyb3NvZnQgT3BlcmF0aW9ucyBQdWVydG8gUmljbzEWMBQG
# A1UEBRMNMjMwMjU0KzQ2NDU2MjAfBgNVHSMEGDAWgBRIbmTlUAXTgqoXNzcitW2o
# ynUClTBUBgNVHR8ETTBLMEmgR6BFhkNodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20v
# cGtpb3BzL2NybC9NaWNDb2RTaWdQQ0EyMDExXzIwMTEtMDctMDguY3JsMGEGCCsG
# AQUFBwEBBFUwUzBRBggrBgEFBQcwAoZFaHR0cDovL3d3dy5taWNyb3NvZnQuY29t
# L3BraW9wcy9jZXJ0cy9NaWNDb2RTaWdQQ0EyMDExXzIwMTEtMDctMDguY3J0MAwG
# A1UdEwEB/wQCMAAwDQYJKoZIhvcNAQELBQADggIBABRKE3yDcJHa8xnyFn9Z+0m8
# vQLeUGC9933o78aSOWDkvcPFPczSqvw4cUmQnHPcRwDS1mwlYs5TmCdIS6Ij++Or
# uWxfgMdPRpveO6zT8rDWBL2sqCT/k5yCO75DVhT4kE/qEe81T4OY/Ejx3lZbBE1a
# z2k5dOL/ZWqNu8FdKSDmBZEeENOYy9UIyLf6coV2KLERB2IZ3W8U3z37fPA5nRMw
# +9sWWb98Gdm8exr4UwmnU0q8Y0KvJx/xwqOPShgiDjHsWev3fzsKSYzebkfBdLbw
# DZl9880mrGr03CfEWGDWa0tJui3LRh4csIuxWHkUrFw/R2N8baMDGPEUCh7dE+qf
# nuuMJ5tRUmnMOqyqj8dLXUZa+yxxpS91qde5asle0+WfzjLQ1D+T6ElhLBQU9LNh
# 5nhbD1+kJkVHFAU2tM3MXa2tgMVWFWQP4IqcQDWMW68M90VkGUrJ+t63oRO8HwbL
# 4IZJxG0wW/527ypSQTmpLSX6mM2vIyFHsO4zCvjDq8yfnDk25bpUNJbfOpqVkkWP
# UE+4bNIQbzcWgKgPIZDOka3pxq4vI05ns3tnvWS7TKiG+7ZYr5ZBSS6pr1Wykt0U
# aXxaUZuAWwikj2gvZAXR35f5bDg+36WoJTpQKNqzsY7dyL6SxkcZI8DcEKWEfbWd
# BX8q+w5hzEWqh7TrYJ93MIIHejCCBWKgAwIBAgIKYQ6Q0gAAAAAAAzANBgkqhkiG
# 9w0BAQsFADCBiDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAO
# BgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEy
# MDAGA1UEAxMpTWljcm9zb2Z0IFJvb3QgQ2VydGlmaWNhdGUgQXV0aG9yaXR5IDIw
# MTEwHhcNMTEwNzA4MjA1OTA5WhcNMjYwNzA4MjEwOTA5WjB+MQswCQYDVQQGEwJV
# UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UE
# ChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSgwJgYDVQQDEx9NaWNyb3NvZnQgQ29k
# ZSBTaWduaW5nIFBDQSAyMDExMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKC
# AgEAq/D6chAcLq3YbqqCEE00uvK2WCGfQhsqa+laUKq4BjgaBEm6f8MMHt03a8YS
# 2AvwOMKZBrDIOdUBFDFC04kNeWSHfpRgJGyvnkmc6Whe0t+bU7IKLMOv2akrrnoJ
# r9eWWcpgGgXpZnboMlImEi/nqwhQz7NEt13YxC4Ddato88tt8zpcoRb0RrrgOGSs
# bmQ1eKagYw8t00CT+OPeBw3VXHmlSSnnDb6gE3e+lD3v++MrWhAfTVYoonpy4BI6
# t0le2O3tQ5GD2Xuye4Yb2T6xjF3oiU+EGvKhL1nkkDstrjNYxbc+/jLTswM9sbKv
# kjh+0p2ALPVOVpEhNSXDOW5kf1O6nA+tGSOEy/S6A4aN91/w0FK/jJSHvMAhdCVf
# GCi2zCcoOCWYOUo2z3yxkq4cI6epZuxhH2rhKEmdX4jiJV3TIUs+UsS1Vz8kA/DR
# elsv1SPjcF0PUUZ3s/gA4bysAoJf28AVs70b1FVL5zmhD+kjSbwYuER8ReTBw3J6
# 4HLnJN+/RpnF78IcV9uDjexNSTCnq47f7Fufr/zdsGbiwZeBe+3W7UvnSSmnEyim
# p31ngOaKYnhfsi+E11ecXL93KCjx7W3DKI8sj0A3T8HhhUSJxAlMxdSlQy90lfdu
# +HggWCwTXWCVmj5PM4TasIgX3p5O9JawvEagbJjS4NaIjAsCAwEAAaOCAe0wggHp
# MBAGCSsGAQQBgjcVAQQDAgEAMB0GA1UdDgQWBBRIbmTlUAXTgqoXNzcitW2oynUC
# lTAZBgkrBgEEAYI3FAIEDB4KAFMAdQBiAEMAQTALBgNVHQ8EBAMCAYYwDwYDVR0T
# AQH/BAUwAwEB/zAfBgNVHSMEGDAWgBRyLToCMZBDuRQFTuHqp8cx0SOJNDBaBgNV
# HR8EUzBRME+gTaBLhklodHRwOi8vY3JsLm1pY3Jvc29mdC5jb20vcGtpL2NybC9w
# cm9kdWN0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFfMDNfMjIuY3JsMF4GCCsGAQUF
# BwEBBFIwUDBOBggrBgEFBQcwAoZCaHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3Br
# aS9jZXJ0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFfMDNfMjIuY3J0MIGfBgNVHSAE
# gZcwgZQwgZEGCSsGAQQBgjcuAzCBgzA/BggrBgEFBQcCARYzaHR0cDovL3d3dy5t
# aWNyb3NvZnQuY29tL3BraW9wcy9kb2NzL3ByaW1hcnljcHMuaHRtMEAGCCsGAQUF
# BwICMDQeMiAdAEwAZQBnAGEAbABfAHAAbwBsAGkAYwB5AF8AcwB0AGEAdABlAG0A
# ZQBuAHQALiAdMA0GCSqGSIb3DQEBCwUAA4ICAQBn8oalmOBUeRou09h0ZyKbC5YR
# 4WOSmUKWfdJ5DJDBZV8uLD74w3LRbYP+vj/oCso7v0epo/Np22O/IjWll11lhJB9
# i0ZQVdgMknzSGksc8zxCi1LQsP1r4z4HLimb5j0bpdS1HXeUOeLpZMlEPXh6I/MT
# faaQdION9MsmAkYqwooQu6SpBQyb7Wj6aC6VoCo/KmtYSWMfCWluWpiW5IP0wI/z
# Rive/DvQvTXvbiWu5a8n7dDd8w6vmSiXmE0OPQvyCInWH8MyGOLwxS3OW560STkK
# xgrCxq2u5bLZ2xWIUUVYODJxJxp/sfQn+N4sOiBpmLJZiWhub6e3dMNABQamASoo
# PoI/E01mC8CzTfXhj38cbxV9Rad25UAqZaPDXVJihsMdYzaXht/a8/jyFqGaJ+HN
# pZfQ7l1jQeNbB5yHPgZ3BtEGsXUfFL5hYbXw3MYbBL7fQccOKO7eZS/sl/ahXJbY
# ANahRr1Z85elCUtIEJmAH9AAKcWxm6U/RXceNcbSoqKfenoi+kiVH6v7RyOA9Z74
# v2u3S5fi63V4GuzqN5l5GEv/1rMjaHXmr/r8i+sLgOppO6/8MO0ETI7f33VtY5E9
# 0Z1WTk+/gFcioXgRMiF670EKsT/7qMykXcGhiJtXcVZOSEXAQsmbdlsKgEhr/Xmf
# wb1tbWrJUnMTDXpQzTGCFVMwghVPAgEBMIGVMH4xCzAJBgNVBAYTAlVTMRMwEQYD
# VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNpZ25p
# bmcgUENBIDIwMTECEzMAAAIZjAqfshYrEOYAAAAAAhkwDQYJYIZIAWUDBAIBBQCg
# gaYwGQYJKoZIhvcNAQkDMQwGCisGAQQBgjcCAQQwHAYKKwYBBAGCNwIBCzEOMAwG
# CisGAQQBgjcCARUwLwYJKoZIhvcNAQkEMSIEIHc1wijBS9Tjg2C2qfcGNY6nSZs5
# vAizGGDPyxZvxQDGMDoGCisGAQQBgjcCAQwxLDAqoAyACgBTAGsAeQBwAGWhGoAY
# aHR0cDovL3d3dy5taWNyb3NvZnQuY29tMA0GCSqGSIb3DQEBAQUABIIBAEloExOv
# jCP7nvTlk/G6QAAwExFOCx/TL+ab/EhqitCO9phFLt6xAlnx95+YoqYXqf9Aimzv
# +gVERg3zjuE7e3XyFGOCkKkub0BEz4XZv2fABkjfbRFlV3ZPwIXGEb9aiiXeyuPF
# tHHEX50y0j6y0LHCd/tndag1nrwipeMCwHth6Z1Iz5nH1Fmb8PlXzBB/IkmsWoBO
# m5WePAXZjvawzcyftR6am361HbGmOIC8FXljewwLt5rSkvV4/YXcvkzto5zMBzBm
# G7zYcGWMLY8cyO6RQ9rAPw0aGTKmtbrN4EGjzyEcd92ViDjoclY2Iymr54o0vwoz
# xxddRs2TmR6DU7mhghLlMIIS4QYKKwYBBAGCNwMDATGCEtEwghLNBgkqhkiG9w0B
# BwKgghK+MIISugIBAzEPMA0GCWCGSAFlAwQCAQUAMIIBUQYLKoZIhvcNAQkQAQSg
# ggFABIIBPDCCATgCAQEGCisGAQQBhFkKAwEwMTANBglghkgBZQMEAgEFAAQgz64q
# vt9tRxd7EZkZNkZrfLU1dcPJKpFq5pxFmUtYAhcCBmFDm9r1phgTMjAyMTA5MzAx
# NjMzMDUuNTE0WjAEgAIB9KCB0KSBzTCByjELMAkGA1UEBhMCVVMxEzARBgNVBAgT
# Cldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29m
# dCBDb3Jwb3JhdGlvbjElMCMGA1UECxMcTWljcm9zb2Z0IEFtZXJpY2EgT3BlcmF0
# aW9uczEmMCQGA1UECxMdVGhhbGVzIFRTUyBFU046NDlCQy1FMzdBLTIzM0MxJTAj
# BgNVBAMTHE1pY3Jvc29mdCBUaW1lLVN0YW1wIFNlcnZpY2Wggg48MIIE8TCCA9mg
# AwIBAgITMwAAAUmACEq7CaAzCwAAAAABSTANBgkqhkiG9w0BAQsFADB8MQswCQYD
# VQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEe
# MBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSYwJAYDVQQDEx1NaWNyb3Nv
# ZnQgVGltZS1TdGFtcCBQQ0EgMjAxMDAeFw0yMDExMTIxODI1NTdaFw0yMjAyMTEx
# ODI1NTdaMIHKMQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4G
# A1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSUw
# IwYDVQQLExxNaWNyb3NvZnQgQW1lcmljYSBPcGVyYXRpb25zMSYwJAYDVQQLEx1U
# aGFsZXMgVFNTIEVTTjo0OUJDLUUzN0EtMjMzQzElMCMGA1UEAxMcTWljcm9zb2Z0
# IFRpbWUtU3RhbXAgU2VydmljZTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoC
# ggEBAK8T+4kPhdh22no5Khk+SiUb2ncJZzAuV7VeRAyW4R6M3MhAx5Yyx3xlu6N1
# +Ml9Yb9zdI6ZkHBQBYR9VJ2UJoxrK3yBAeQoWKSgP9tjVDjLtF91ruwInDwJd/nB
# 8urOwYy8qSG0EUY6Go39ipCbmPsHRz2qrXbyLjSWuuyk6bfVV6X5QCqVW3Uvslvk
# wYoxaYRqhCmC8sZCr008EMx2BWObVfAUVVyl4FFZafdVvRQJYDq2pG4Usto6yF5g
# ID+PDrPDf5TAhObcmadBUwiv0cAuC8pja5LuWdIqIRopGNvWgHW/RTSzxY/OSBtW
# mzKuj5SaXa/tWt5qDNDPC9H51a0CAwEAAaOCARswggEXMB0GA1UdDgQWBBRWd5rx
# o++4tLw1NdZPyalz6m8kgTAfBgNVHSMEGDAWgBTVYzpcijGQ80N7fEYbxTNoWoVt
# VTBWBgNVHR8ETzBNMEugSaBHhkVodHRwOi8vY3JsLm1pY3Jvc29mdC5jb20vcGtp
# L2NybC9wcm9kdWN0cy9NaWNUaW1TdGFQQ0FfMjAxMC0wNy0wMS5jcmwwWgYIKwYB
# BQUHAQEETjBMMEoGCCsGAQUFBzAChj5odHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20v
# cGtpL2NlcnRzL01pY1RpbVN0YVBDQV8yMDEwLTA3LTAxLmNydDAMBgNVHRMBAf8E
# AjAAMBMGA1UdJQQMMAoGCCsGAQUFBwMIMA0GCSqGSIb3DQEBCwUAA4IBAQAQ3ngL
# PiDs4EqpzyLCovM11CPY4JPEqYf6OvcDKn4Bj/WrDh3vsD/hYI/yDw91OhiILjtR
# cLoV3Z6knTs6V6fnR/zysUDPj0fkFXteXA+OLITVlTS8soeIJwHaaJtqW6LtbR22
# DhbhsiqLtSVCSEEsRFLmef7MdhCD+sVBRC+8msqnHY0zQwWC/aGSLgHcmQNR8XCg
# fFhsAAlHVS1dof7Q8bUFbnIvUMuzjnWrsP9Gwcaa/HUzr5EpKveoJSJxt9ARry9o
# /6conRP8Nrm9KqlIqhx8Px3AzdSefS2mgL6UqapAwNuWWCEazs1WGmz73Eb3mztt
# 4IyvcC5Rkb8TpFBpMIIGcTCCBFmgAwIBAgIKYQmBKgAAAAAAAjANBgkqhkiG9w0B
# AQsFADCBiDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNV
# BAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEyMDAG
# A1UEAxMpTWljcm9zb2Z0IFJvb3QgQ2VydGlmaWNhdGUgQXV0aG9yaXR5IDIwMTAw
# HhcNMTAwNzAxMjEzNjU1WhcNMjUwNzAxMjE0NjU1WjB8MQswCQYDVQQGEwJVUzET
# MBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMV
# TWljcm9zb2Z0IENvcnBvcmF0aW9uMSYwJAYDVQQDEx1NaWNyb3NvZnQgVGltZS1T
# dGFtcCBQQ0EgMjAxMDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKkd
# Dbx3EYo6IOz8E5f1+n9plGt0VBDVpQoAgoX77XxoSyxfxcPlYcJ2tz5mK1vwFVMn
# BDEfQRsalR3OCROOfGEwWbEwRA/xYIiEVEMM1024OAizQt2TrNZzMFcmgqNFDdDq
# 9UeBzb8kYDJYYEbyWEeGMoQedGFnkV+BVLHPk0ySwcSmXdFhE24oxhr5hoC732H8
# RsEnHSRnEnIaIYqvS2SJUGKxXf13Hz3wV3WsvYpCTUBR0Q+cBj5nf/VmwAOWRH7v
# 0Ev9buWayrGo8noqCjHw2k4GkbaICDXoeByw6ZnNPOcvRLqn9NxkvaQBwSAJk3jN
# /LzAyURdXhacAQVPIk0CAwEAAaOCAeYwggHiMBAGCSsGAQQBgjcVAQQDAgEAMB0G
# A1UdDgQWBBTVYzpcijGQ80N7fEYbxTNoWoVtVTAZBgkrBgEEAYI3FAIEDB4KAFMA
# dQBiAEMAQTALBgNVHQ8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAW
# gBTV9lbLj+iiXGJo0T2UkFvXzpoYxDBWBgNVHR8ETzBNMEugSaBHhkVodHRwOi8v
# Y3JsLm1pY3Jvc29mdC5jb20vcGtpL2NybC9wcm9kdWN0cy9NaWNSb29DZXJBdXRf
# MjAxMC0wNi0yMy5jcmwwWgYIKwYBBQUHAQEETjBMMEoGCCsGAQUFBzAChj5odHRw
# Oi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpL2NlcnRzL01pY1Jvb0NlckF1dF8yMDEw
# LTA2LTIzLmNydDCBoAYDVR0gAQH/BIGVMIGSMIGPBgkrBgEEAYI3LgMwgYEwPQYI
# KwYBBQUHAgEWMWh0dHA6Ly93d3cubWljcm9zb2Z0LmNvbS9QS0kvZG9jcy9DUFMv
# ZGVmYXVsdC5odG0wQAYIKwYBBQUHAgIwNB4yIB0ATABlAGcAYQBsAF8AUABvAGwA
# aQBjAHkAXwBTAHQAYQB0AGUAbQBlAG4AdAAuIB0wDQYJKoZIhvcNAQELBQADggIB
# AAfmiFEN4sbgmD+BcQM9naOhIW+z66bM9TG+zwXiqf76V20ZMLPCxWbJat/15/B4
# vceoniXj+bzta1RXCCtRgkQS+7lTjMz0YBKKdsxAQEGb3FwX/1z5Xhc1mCRWS3Tv
# QhDIr79/xn/yN31aPxzymXlKkVIArzgPF/UveYFl2am1a+THzvbKegBvSzBEJCI8
# z+0DpZaPWSm8tv0E4XCfMkon/VWvL/625Y4zu2JfmttXQOnxzplmkIz/amJ/3cVK
# C5Em4jnsGUpxY517IW3DnKOiPPp/fZZqkHimbdLhnPkd/DjYlPTGpQqWhqS9nhqu
# BEKDuLWAmyI4ILUl5WTs9/S/fmNZJQ96LjlXdqJxqgaKD4kWumGnEcua2A5HmoDF
# 0M2n0O99g/DhO3EJ3110mCIIYdqwUB5vvfHhAN/nMQekkzr3ZUd46PioSKv33nJ+
# YWtvd6mBy6cJrDm77MbL2IK0cs0d9LiFAR6A+xuJKlQ5slvayA1VmXqHczsI5pgt
# 6o3gMy4SKfXAL1QnIffIrE7aKLixqduWsqdCosnPGUFN4Ib5KpqjEWYw07t0Mkvf
# Y3v1mYovG8chr1m1rtxEPJdQcdeh0sVV42neV8HR3jDA/czmTfsNv11P6Z0eGTgv
# vM9YBS7vDaBQNdrvCScc1bN+NR4Iuto229Nfj950iEkSoYICzjCCAjcCAQEwgfih
# gdCkgc0wgcoxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYD
# VQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xJTAj
# BgNVBAsTHE1pY3Jvc29mdCBBbWVyaWNhIE9wZXJhdGlvbnMxJjAkBgNVBAsTHVRo
# YWxlcyBUU1MgRVNOOjQ5QkMtRTM3QS0yMzNDMSUwIwYDVQQDExxNaWNyb3NvZnQg
# VGltZS1TdGFtcCBTZXJ2aWNloiMKAQEwBwYFKw4DAhoDFQA/5bGu5y70ZIibAB0P
# nYFEa6mod6CBgzCBgKR+MHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5n
# dG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9y
# YXRpb24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEwMA0G
# CSqGSIb3DQEBBQUAAgUA5P/mRTAiGA8yMDIxMDkzMDE1MzExN1oYDzIwMjExMDAx
# MTUzMTE3WjB3MD0GCisGAQQBhFkKBAExLzAtMAoCBQDk/+ZFAgEAMAoCAQACAgqP
# AgH/MAcCAQACAhFiMAoCBQDlATfFAgEAMDYGCisGAQQBhFkKBAIxKDAmMAwGCisG
# AQQBhFkKAwKgCjAIAgEAAgMHoSChCjAIAgEAAgMBhqAwDQYJKoZIhvcNAQEFBQAD
# gYEAdnSXXEot683UbpI1OixWcs6GycrjGAAvq7jfO1xQABQ/p9vtX0fy57wdDAKi
# uMXg+GeXhgm1q/Hx1j/LoMTb9rrz4oYrOd7EuM1GlEwPNDS0C6VY56Cga7ZRjf1+
# eNManlcQgLakeHHIMmTevsiRXHPTMHBjbhHEfvgeT4552xwxggMNMIIDCQIBATCB
# kzB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
# UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSYwJAYDVQQD
# Ex1NaWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAxMAITMwAAAUmACEq7CaAzCwAA
# AAABSTANBglghkgBZQMEAgEFAKCCAUowGgYJKoZIhvcNAQkDMQ0GCyqGSIb3DQEJ
# EAEEMC8GCSqGSIb3DQEJBDEiBCBgiNvOYvg8kbWjNOT3Wf4HNehHClZvd0uP7Sjf
# hnFYnTCB+gYLKoZIhvcNAQkQAi8xgeowgecwgeQwgb0EICiV+vxYfXjvzN2GeBB1
# KpzsNAvSxnHQ5cb1rR+56KGyMIGYMIGApH4wfDELMAkGA1UEBhMCVVMxEzARBgNV
# BAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jv
# c29mdCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUtU3RhbXAg
# UENBIDIwMTACEzMAAAFJgAhKuwmgMwsAAAAAAUkwIgQgkAetWcAMKoy4Jyq2hSqd
# StDUO9OfXTfYiZmQ7RA0+jgwDQYJKoZIhvcNAQELBQAEggEAHqstHA0/g3yeKgSB
# KP1dPOAL1LBzmtBjHAIAAzku8r0J/xxBiaWFewcfzvoM2zdnhbQ9OfFgTPH4NLgq
# MFVlcG3g+fFAl7pH2P/u1z+aV3Xbi+cQsSfZH5TeLm9KXcEtJMa1Ofy999GMmdEy
# 5ed+IBY7sIX/VU8lwHkOZScZcMqCqHmBXAmiU5TCyIYgDPw439nUeFI1f2q5AuGw
# 6ZAlUpf4rETDmfrbYK0Z/pdDwhsN9mPe8xK7NxQZGTbVXz9uOLwW8PsQMnjLSD3o
# daurxkceRNGoOaLt/Q3UiZCw4bU5UlDXvLu/6t6XO0thFv798boaRAJl6kOmMAd7
# ogRdGQ==
# SIG # End signature block
